.github/workflows/quay.io.cephcsi.cephcsi.v3.4.0.yaml
quay.io/cephcsi/cephcsi/v3.4.0/Dockerfile

This supports [CASMPET-5006](https://connect.us.cray.com/jira/browse/CASMPET-5006) and is required by https://github.com/Cray-HPE/cray-ceph-csi-cephfs/pull/4 in order to resolve vulnerabilities.

Add quay.io/cephcsi/cephcsi:v3.4.0

---

.github/workflows/k8s.gcr.io.sig-storage.csi-attacher.v3.4.0.yaml
.github/workflows/k8s.gcr.io.sig-storage.csi-node-driver-registrar.v2.4.0.yaml
.github/workflows/k8s.gcr.io.sig-storage.csi-provisioner.v3.1.0.yaml
.github/workflows/k8s.gcr.io.sig-storage.csi-resizer.v1.3.0.yaml
.github/workflows/k8s.gcr.io.sig-storage.csi-snapshotter.v4.2.0.yaml
.github/workflows/quay.io.cephcsi.cephcsi.v3.5.1.yaml
k8s.gcr.io/sig-storage/csi-attacher/v3.4.0/Dockerfile
k8s.gcr.io/sig-storage/csi-node-driver-registrar/v2.4.0/Dockerfile
k8s.gcr.io/sig-storage/csi-provisioner/v3.1.0/Dockerfile
k8s.gcr.io/sig-storage/csi-resizer/v1.3.0/Dockerfile
k8s.gcr.io/sig-storage/csi-snapshotter/v4.2.0/Dockerfile
quay.io/cephcsi/cephcsi/v3.5.1/Dockerfile

This is to support ceph csi 3.5.1 and our ability to update the upgrade strategy.
This is to support ceph csi 3.5.1 and our ability to update the upgrade strategy.
* Resolves CASMINST-3857
Building the images to test. Will update after testing is complete

CASMINST-3857 Update container images for ceph-csi

---

.github/workflows/docker.io.alpine.git.2.32.0.yaml
docker.io/alpine/git/2.32.0/Dockerfile

There are CVE vulnerabilities in the base image that are resolved by a rebuild but it looks like the official image isn't rebuilt on a regular basis.  Moving this into here to rebuild and give us a patched version that we can use.
* Resolves [CSAMCMS-7817](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7817)
Built the image manually on local box and used snyk to determine that a rebuild will resolve the vulnerabilities.
Low risk - just running update on the provided base image.

CASMCMS-7817 - CVE vulnerabilities in dckr.io/alpine/git:v2.32.0.

---

.github/workflows/velero.velero.v1.6.3.yaml
velero/velero/v1.6.3/Dockerfile

Adding Velero 1.6.3 container image.  This is required as a step upgrade moving towards 1.7.x and then 1.8.x
* Resolves CASMPET-5339
* Not tested yet

CASMPET-5339 - Add velero 1.6.3 image

---

.github/workflows/k8s.gcr.io.kube-apiserver.v1.20.15.yaml
.github/workflows/k8s.gcr.io.kube-controller-manager.v1.20.15.yaml
.github/workflows/k8s.gcr.io.kube-proxy.v1.20.15.yaml
.github/workflows/k8s.gcr.io.kube-scheduler.v1.20.15.yaml
k8s.gcr.io/kube-apiserver/v1.20.15/Dockerfile
k8s.gcr.io/kube-controller-manager/v1.20.15/Dockerfile
k8s.gcr.io/kube-proxy/v1.20.15/Dockerfile
k8s.gcr.io/kube-scheduler/v1.20.15/Dockerfile

Add newer k8s images to dodge CVE in 1.20.13
* Resolves [CASMINST-4083](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4083)
Not yet
Not yet
Not yet

Add k8s 1.20.15 images

---

quay.io/ceph/ceph/v15.2.15/Dockerfile
quay.io/ceph/ceph/v16.2.7/Dockerfile

Disables an unused upstream repo so the image can  patch correctly via the action
* Resolves CASMPET-5351

Disables an unused upstream repo.

---

.github/workflows/registry.opensource.zalan.do.acid.pgbouncer.master-21.yaml
registry.opensource.zalan.do/acid/pgbouncer/master-21/Dockerfile

Add pgbouncer master-21 docker image from upstream. The master-19 docker image we currently use is based on alpine 3.12.8, with 0 critical and 10 high CVEs. The new master-21 docker image is based on alpine 3.12.9, with 0 critical and only 1 high CVE.
* Resolves [CASMINST-4082]
Will be tested with a new chart PR on a bare metal system or vshasta.
Low. This is minor release update.

CASMINST-4082: add pgbouncer master-21 release from upstream

---

.github/workflows/docker.io.openpolicyagent.opa.0.26.0-envoy-6.yaml
docker.io/openpolicyagent/opa/0.26.0-envoy-6/Dockerfile

Rebuild OPA Envoy plugin upstream image v0.26.0-envoy-6 for istio 1.9 upgrade. The current OPA plugin image we're using (v0.24.0-envoy-1) does not support XDS v3 authz api in istio 1.9.
* Resolves [CASMPET-5369]
The upstream image was tested in vshasta environment. Will test the rebuilt image again with istio 1.9 upgrade changes.
Low.

CASMPET-5369: OPA Envoy plugin v0.26.0-envoy-6 for istio 1.9 upgrade

---

.github/workflows/docker.io.library.golang.1.17.3-alpine3.15.yaml
docker.io/library/golang/1.17.3-alpine3.15/Dockerfile

Add golang.1.17.3-alpine3.15 version docker image
- Resolves [CASMINST-4144](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4144)
N/A
N/A
N/A
N/A

CASMINST-4144: Add alpine3.15 version of golang.

---

.github/workflows/docker.io.gitea.gitea.1.16.4-rootless.yaml
docker.io/gitea/gitea/1.16.4-rootless/Dockerfile

The previous version of gitea docker.io/gitea/gitea:1.15.3-rootless has a CVE vulnerability in its base image.  The fix to patch the image in place was not cleared for inclusion into csm-1.2, so we had to create a new updated version with a different tag to resolve this in csm-1.2.5 and later releases.
The update gitea image now provides a rootless base image, so rather than building it ourselves like we had to do for the 1.15.3 version, we have reverted to pulling the provided image directly and just applying security patches to it.
* Resolves [CASMINST-4257](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4257)
* Change will also be needed in https://github.com/Cray-HPE/gitea to pull this image.
No testing done at this stage - need to get the image  built and accessible before I …

CASMINST-4257 - create image docker.io/gitea/gitea:1.16.4-rootless.

---

.github/workflows/quay.io.kiali.kiali-operator.v1.33.1.yaml
.github/workflows/quay.io.kiali.kiali.v1.33.1.yaml
quay.io/kiali/kiali-operator/v1.33.1/Dockerfile
quay.io/kiali/kiali/v1.33.1/Dockerfile

With the upgrade of istio to 1.9 we need to pick up a new version of kiali. 1.33.1 is the latest that is compatible with istio 1.9.

CASMPET-5303: Build kiali* v1.33.1 images

---

.github/workflows/docker.io.library.redis.5.0-alpine3.14.yaml
docker.io/library/redis/5.0-alpine3.14/Dockerfile

Add the redis 5.0 alpine 3.14 image to be automatically patched with security updates.
* Resolves [CASMCMS-7965](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7965)
* Change will also be needed in `cray-cfs-api` to use this new version of the image
Just adding a new base image that is being rebuilt by container-images for security patches.

Add docker.io/library/redis.5.0-alpine3.14 image.

---

.github/workflows/quay.io.oauth2-proxy.oauth2-proxy.v7.2.1.yaml
docker.io/timothyb89/monasca-sidecar/1.0.0/Dockerfile
quay.io/oauth2-proxy/oauth2-proxy/v7.2.1/Dockerfile

The upstream oauth2-proxy image uses an older version of alpine image (3.15.0) with a few critical or high CVEs. By rebuilding it in our repo, we can improve the turn-around time for CVE remediation.
* Resolves [CASMPET-5534]
Will test with chart changes after image is rebuilt. …

CASMPET-5534: rebuild oauth2-proxy container image

---

.github/workflows/docker.io.python.slim-bullseye.yaml
docker.io/python/slim-bullseye/Dockerfile

Add `python:slim-bullseye` image for to use as `canu` base.
* Resolves [CASMINST-4481](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4481)

CASMINST-4481 Provide locally rebuilt python:bullseye

---

quay.io/galexrt/node-exporter-smartmon/v0.1.1/Dockerfile

Earlier node-exporter image uses Debian package which tends to have higher CVE counts. Now changed it to more secure alpine as base OS image for node-exporter to reduce CVE counts.
* Resolves: https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-145
Slice and Frigg

CASMMON-145: change node-exporter image base Debian package

---

.github/workflows/sdlc-ops.wait-for-it.1.0.0.yaml
docker.io/sdlc-ops/wait-for-it/1.0.0/Dockerfile
docker.io/sdlc-ops/wait-for-it/1.0.0/LICENSE
sdlc-ops/wait-for-it/1.0.0/Dockerfile
sdlc-ops/wait-for-it/1.0.0/LICENSE

Move wait-for-it image used by spire-tokens chart into this repo to allow an easier automatic rebuild for CVE remediation.
* Partially resolves [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
* Future work required by [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
To be tested after the image is published.
- Was downgrade …

CASMINST-4505: build wait-for-it image in the repo

---

sdlc-ops/wait-for-it/1.0.0/Dockerfile
sdlc-ops/wait-for-it/1.0.0/wait-for-it.sh

The wget command does not download the script as expected. This PR addresses this issue.
* Partially resolves [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
* Future work required by [CASMINST-4505](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4505)
Be to fully tested when published.
- Were new tests (or …

CASMINST-4505: fix script download issue in wait-for-it

---

munge-munge/1.1.3/Dockerfile

The image is based on sle15 sp3, but the zypper updates were pulling from sp2 repos.  This corrects the dockerfile to point the updates to the correct repo locations for the service pack of the base image.
* Resolves [CASMCMS-8006](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8006)
* Build system
This image is only used by cray-crus.  There are no systems installed with the correct required products to be able to run crus, so there is no way to test this.
This is a very minor change and if it builds successfully it should be correct.

CASMCMS-8006 - Update munge-munge image to pull updates from correct location.

---

.github/workflows/k8s.gcr.io.pause.3.4.1.yaml
k8s.gcr.io/pause/3.4.1/Dockerfile

Adding new version of pause to support k8s v1.21.12
* Resolves CASMINST-4743

Adding newer pause version for k8s

---

.github/workflows/docker.io.registry.2.8.1.yaml
docker.io/registry/2.8.1/Dockerfile

Adding docker registry.  Ceph has a requirement of the active registry to pull new images from.  Nexus will not be functional at the point ceph needs to attempt the pull. 
* Resolves CASMPET-5694

Adding docker registry that will run locally on the storage nodes

---

.github/workflows/docker.io.library.alpine.3.16.yaml
docker.io/library/alpine/3.16/Dockerfile

This change adds build files for the latest alpine:3.16 base image to algol60 artifactory.
* N/A, but needed for [CASMHMS-5586](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5586).
Was a fresh Install tested? N
Was an Upgrade tested? N
Was a Downgrade tested? N
Low risk.

Add alpine:3.16 container image.

---

munge-munge/1.1.3/Dockerfile

Fixing directory permissions on munge image so that the munged process can run correctly as a non-root user.
* Resolves [CASMTRIAGE-3526](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3526)
* Change will also be needed in `cray-crus` to the helm chart to run this container under the correct user.
* `Hela`
Had to create the image locally with these changes as best I could build (don't have permissions to access internal repos from my local build), then uploaded the image to Hela and tested there.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? Y
- Was upgrade tested? If not, why? N - just an image
- Was downgrade tested? If not, why? N - just an image
- Were new tests (or …

CASMTRIAGE-3526 - fix dir permissions on munge-munge image.

---

.github/workflows/quay.io.cilium.cilium.v1.11.6.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.11.6.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.11.6.yaml
quay.io/cilium/cilium/v1.11.6/Dockerfile
quay.io/cilium/hubble-relay/v1.11.6/Dockerfile
quay.io/cilium/operator-generic/v1.11.6/Dockerfile

Adds the following container images:
* quay.io.cilium.cilium:v1.11.6
* quay.io.cilium.hubble-relay:v1.11.6
* quay.io.cilium.operator-generic:v1.11.6
* Resolves CASMPET-5763

CASMPET-5763: Add cilium container images to artifactory

---

.github/workflows/quay.io.oauth2-proxy.oauth2-proxy.v7.3.0.yaml
quay.io/oauth2-proxy/oauth2-proxy/v7.3.0/Dockerfile

oauth2-proxy published a new image v7.3.0 which removed the alpine image pinning. It will help us with CVE remediation.
* Partially Resolves [CASMPET-5697](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5697)
* Future work required by [CASMPET-5697](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5697)
Will be tested after the container image is rebuilt and published.
_How were the changes tested and success verified? If schema …

CASMPET-5697: Add oauth2-proxy v7.3.0 image

---

.github/workflows/docker.io.openpolicyagent.opa.0.42.1-envoy.yaml
docker.io/openpolicyagent/opa/0.42.1-envoy/Dockerfile

Adding latest opa-envoy container for use with cray-opa chart.
* [CASMPET-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5793)

CASMPET-5793 Add opa 0.4.1-envoy container

---

.github/workflows/quay.io.kiali.kiali-operator.v1.36.7.yaml
.github/workflows/quay.io.kiali.kiali.v1.36.7.yaml
quay.io/kiali/kiali-operator/v1.36.7/Dockerfile
quay.io/kiali/kiali/v1.36.7/Dockerfile

Add kiali & kiali-operator v1.36.7 images for istio 1.10 upgrade. 
* Partially Resolves [CASMPET-5796](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5796)
* Future work required by [CASMPET-5796](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5796)
Will be tested in both vshasta & physical systems after they are merged and published.
- Were …

CASMPET-5796: add kiali v1.36.7 images

---

.github/workflows/quay.io.cilium.cilium.v1.12.0.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.0.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.0.yaml
quay.io/cilium/cilium/v1.12.0/Dockerfile
quay.io/cilium/hubble-relay/v1.12.0/Dockerfile
quay.io/cilium/operator-generic/v1.12.0/Dockerfile

Cilium released version v1.12.0 this week.  Adding the v.1.12.0 container images to artifactory.
Adds the following container images:
quay.io.cilium.cilium:v1.12.0
quay.io.cilium.hubble-relay:v1.12.0
quay.io.cilium.operator-generic:v1.12.0
* Resolves CASMPET-5820

CASMPET-5820:  Add cilium v1.12.0 container images to artifactory

---

quay.io/kiali/kiali/v1.36.7/Dockerfile

Use the user id of kiali instead of username to prevent the unknown user error when running as non-root.
* Resolves [CASMPET-5796](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5796)
* Future work required by [CASMPET-5796](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5796)
Using kiali username caused the following error:
"Error: container has runAsNonRoot and image has non-numeric user (kiali), cannot verify user is non-root"
Will validate the above error is fixed.
- Were continuous …

CASMPET-5796: use kiali user id

---

.github/workflows/k8s.gcr.io.sig-storage.csi-resizer.v1.4.0.yaml
.github/workflows/quay.io.cephcsi.cephcsi.v3.6.2.yaml
k8s.gcr.io/sig-storage/csi-resizer/v1.4.0/Dockerfile
quay.io/cephcsi/cephcsi/v3.6.2/Dockerfile

Ceph-csi version bump for 1.3. This updated quay.io/cephcsi/cephcsi and k8s.gcr.io/sig-storage/csi-resizer.

CASMPET-5778 bump ceph-csi versions for 1.3

---

.github/workflows/munge-munge.1.1.3.yaml
.github/workflows/registry.suse.com.suse.sle15.15.3.yaml
.github/workflows/registry.suse.com.suse.sle15.15.4.yaml
munge-munge/1.1.3/Dockerfile
munge-munge/1.1.3/zypper.sh
registry.suse.com/suse/sle15/15.3/Dockerfile
registry.suse.com/suse/sle15/15.3/zypper.sh
registry.suse.com/suse/sle15/15.4/Dockerfile
registry.suse.com/suse/sle15/15.4/zypper.sh

Use docker buildkit secrets to propagate `SLES_REPO_USERNAME` and `SLES_REPO_PASSWORD` into docker build contexts.
* Resolves [CASMSEC-344](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-344)
* Github
Tested locally to ensure that secrets are injected successfully into build, and not recorded in image history:
$ docker build . --secret id=SLES_REPO_PASSWORD,src=SLES_REPO_PASSWORD --secret id=SLES_REPO_USERNAME,src=SLES_REPO_USERNAME --no-cache -t artifactory.algol60.net/csm-docker/stable/registry.suse.com/suse/sle15:15.4
#1 [internal] load build definition from Dockerfile
#1 sha256:c1a15af486ece7b9a035751780e8fd166f90819f96f9b61580c56c90ccf91c87
#1 transferring dockerfile: 37B done
#1 DONE 0.0s
...
#8 exporting to image
#8 …

CASMSEC-344 use docker secrets to avoid build arg exposure in build history

---

.github/workflows/docker.io.grafana.grafana.8.5.9.yaml
docker.io/grafana/grafana/8.5.9/Dockerfile

Upgrade Grafana to 8.5.9 aligned with SMF. Grafana Upgrade and Dashboard improvements by supporting new visualizations.
Support new visualization elements such as pie charts. This change is backward compatible.
Resolves - 
[CASMMON-195](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-195)
Epic Name: Grafana Upgrade and Dashboard improvements by supporting new visualizations
Upgrade grafana to 7.5.11 version to support merge transform operator in grafana dashboard while merging multiple promsql queries for switch metrics to create grafana dashboard.
Future work required - 
[CASMMON-196](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-196)	
[Use pie chart panel in the existing dashboards](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-196)
Version number(s) incremented from …

CASMMON-195 Upgrade to 8.x

---

.github/workflows/quay.io.cilium.cilium.v1.12.2.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.2.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.2.yaml
quay.io/cilium/cilium/v1.12.2/Dockerfile
quay.io/cilium/hubble-relay/v1.12.2/Dockerfile
quay.io/cilium/operator-generic/v1.12.2/Dockerfile

Cilium released version v1.12.2 this week.  Adding the v.1.12.2 container images to artifactory.
Adds the following container images:
quay.io.cilium.cilium:v1.12.2
quay.io.cilium.hubble-relay:v1.12.2
quay.io.cilium.operator-generic:v1.12.2
* Resolves CASMPET-5945

CASMPET-5945: Add cilium v1.12.2 container images to artifactory

---

docker.io/gitea/gitea/1.17.2-rootless/Dockerfile

Adds a new rootless gitea image for 1.17.2 to address CVE issues.
* Related to CASMCMS-8251
Testing will come once the image is built and before we update the gitea chart to use this new image.

Add gitea image to 1.17.2

---

munge-munge/1.1.3/Dockerfile

The change to sp4 as the base image changed the user id of the 'munge' user and broke the security context settings of the helm charts using the image. This reverts that change.
* Resolves [CASMCMS-8288](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8288)
Can't really test until the new image is built - then will verify correct user ID again.
Low risk, broken now and just reverting a change.

CASMCMS-8288: revert sles15sp4 update in the munge-munge container.

---

.github/workflows/docker.io.coredns.coredns.1.10.0.yaml
.github/workflows/quay.io.cilium.alpine-curl.v1.6.0.yaml
.github/workflows/quay.io.cilium.cilium.v1.12.4.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.4.yaml
.github/workflows/quay.io.cilium.json-mock.v1.3.3.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.4.yaml
docker.io/coredns/coredns/1.10.0/Dockerfile
quay.io/cilium/alpine-curl/v1.6.0/Dockerfile
quay.io/cilium/cilium/v1.12.4/Dockerfile
quay.io/cilium/hubble-relay/v1.12.4/Dockerfile
quay.io/cilium/json-mock/v1.3.3/Dockerfile
quay.io/cilium/operator-generic/v1.12.4/Dockerfile

Updating to new v1.12.4 cilium images.
Also updating these three images that are needed to run the "cilium connectivity test".
docker.io/coredns/coredns:1.10.0
quay.io/cilium/alpine-curl:v1.6.0
quay.io/cilium/json-mock:v1.3.3
* Resolves CASMPET-6152

CASMPET-6152: Update container images for cilium v1.12.4

---

docker.io/grok-exporter/grok-exporter/latest/Dockerfile

CASMMON-249: Update the grok-exporter image from version 2 to version 3.
* Resolves: https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-249
Craystack VM and Slice
shreni:~ # docker images | grep grok
artifactory.algol60.net/csm-docker/unstable/docker.io/grok-exporter/grok-exporter              latest    616ef98a1fef   4 years ago    149MB
shreni:~ # docker ps | grep grok
603c0f742e41   artifactory.algol60.net/csm-docker/unstable/docker.io/grok-exporter/grok-exporter   "./grok_exporter -co…"   About a minute ago   Up About a minute …

CASMMON-249: Update the grok-exporter image from version 2 to version 3.

---

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.9.1.yaml
.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.9.yaml
.github/workflows/quay.io.cilium.cilium.v1.11.6.yaml
.github/workflows/quay.io.cilium.cilium.v1.12.0.yaml
.github/workflows/quay.io.cilium.cilium.v1.12.2.yaml
.github/workflows/quay.io.cilium.cilium.v1.12.3.yaml
.github/workflows/quay.io.cilium.json-mock.v1.3.0.yaml

After an error in the shared workflow was fixed, a few of the cilium images started to hit failures.   These are upstream images so I set the fail_on_snyk_error to false as recommended to suppress the error.   I also took care of the same thing on a couple of the multus container images.
* Resolves [CASMPET-6198](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6198)
Verified no failure in the branch build.

CASMPET-6198:  Don't fail cilium, json-mock, and multus builds on snyk errors

---

.github/workflows/registry.opensource.zalan.do.acid.logical-backup.v1.8.2.yaml
.github/workflows/registry.opensource.zalan.do.acid.pgbouncer.master-22.yaml
.github/workflows/registry.opensource.zalan.do.acid.postgres-operator.v1.8.2.yaml
.github/workflows/registry.opensource.zalan.do.acid.spilo-14.2.1-p7.yaml

These are upstream images so I set the fail_on_snyk_error to false as recommended to suppress the error. These all relate to upstream images used by the latest postgres-operator.
* logical-backup.v.1.8.2
* postgres-operator.v1.8.2
* pgbouncer.master-22
* spilo-14.2.1-p7
* Resolves [CASMPET-5476](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5476) partially
Verified on branch build.

CASMINST-5476: Updated `fail_on_snyk_errors: false` on postgres-operator upstream images

---

.github/workflows/docker.io.demisto.boto3py3.1.0.0.43797.yaml
.github/workflows/docker.io.demisto.boto3py3.1.0.0.43797_v1.21.1.yaml
docker.io/demisto/boto3py3/1.0.0.43797/Dockerfile
docker.io/demisto/boto3py3/1.0.0.43797_v1.21.1/Dockerfile

Updating to more recent boto3 package, and include a version that also includes kubectl.
* Resolves [CASMPET-6186](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6186)
```
ncn-m001-e2e75ea1:/home/bklein # kubectl logs -n services $pod post-upgrade-get-snapshot
Waiting for aws credentials to appear...
cluster: cray-bos, key: cray-bos/etcd_migration.snapshot.db, file: /snapshot/snapshot.db
```
```
ncn-m001-e2e75ea1:/home/bklein # kubectl logs -n services $pod post-upgrade-restore-snapshot -f
Waiting for snapshot to appear...
Waiting for snapshot to appear...
statefulset.apps/cray-bos-bitnami-etcd scaled
Waiting for statefulset spec update to be observed...
statefulset rolling update complete 0 pods at revision cray-bos-bitnami-etcd-65c99fc7b...
cluster: cray-bos pvc: …
```

Update boto3 package and provide version with kubectl

---

.github/workflows/docker.io.demisto.boto3py3.kubectl_v1_21_12_1.0.0.43797.yaml

Updating to more recent boto3 package, and include a version that also includes kubectl.
* Resolves [CASMPET-6186](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6186)
```
ncn-m001-e2e75ea1:/home/bklein # kubectl logs -n services $pod post-upgrade-get-snapshot
Waiting for aws credentials to appear...
cluster: cray-bos, key: cray-bos/etcd_migration.snapshot.db, file: /snapshot/snapshot.db
```
```
ncn-m001-e2e75ea1:/home/bklein # kubectl logs -n services $pod post-upgrade-restore-snapshot -f
Waiting for snapshot to appear...
Waiting for snapshot to appear...
statefulset.apps/cray-bos-bitnami-etcd scaled
Waiting for statefulset spec update to be observed...
statefulset rolling update complete 0 pods at revision cray-bos-bitnami-etcd-65c99fc7b...
cluster: cray-bos pvc: …
```

Fix docker repo path for boto3 image

---

.github/workflows/docker.io.opensuse.leap.15.4.yaml
docker.io/opensuse/leap/15.4/Dockerfile

Updating the base image for cray-ims-sshd and cray-ims-kiwi-ng-opensuse-x86_64-builder to use leap:15.4.
* Resolves [CASMCMS-8366](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8366)
None - need to generate the new image before I can use it to test, but this is a direct copy of what is being done with leap:15.2, so it should be straightforward.
Very low risk - nothing else is using this image at this time.

CASMCMS-8366 - add opensuse/leap:15.4 image.

---

.github/workflows/docker.io.openpolicyagent.opa.0.48.0-envoy.yaml
docker.io/openpolicyagent/opa/0.48.0-envoy/Dockerfile

This adds the opa 0.48.0-envoy containers for use with cray-opa.

CASMPET-6311 Add opa 0.48.0 containers

---

.github/workflows/docker.io.prom.prometheus-config-reloader.v0.62.0.yaml
docker.io/prom/prometheus-config-reloader/v0.62.0/Dockerfile

_Upgrade prometheus-operator/prometheus-config-reloader to v0.62.0._
* Resolves [CASMMON-269](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-269)
- Was the upgrade tested? Yes.

CASMMON-269 Upgrade prometheus-operator/prometheus-config-reloader to v0.62.0

---

.github/workflows/docker.io.bitnami.prometheus-operator.v0.63.0.yaml
.github/workflows/docker.io.grafana.grafana.9.3.2.yaml
docker.io/bitnami/prometheus-operator/v0.63.0/Dockerfile

_Upgrade prometheus-operator to version v0.63.0 and fix workflows of last PRs_
* Resolves [CASMMON-267](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-267)
* `hela`
- Was upgrade tested? Yes

CASMMON-267 Upgrade prometheus-operator image

---

.github/workflows/docker.io.bitnami.kube-state-metrics.v2.8.0.yaml
docker.io/bitnami/kube-state-metrics/v2.8.0/Dockerfile

_Upgrade kube-state-metrics image to v2.8.0_
* Resolves [CASMMON-270](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-270)
* `hela`
- Was upgrade tested? Yes.

CASMMON-270 Upgrade kube-state-metrics image

---

.github/workflows/quay.io.kiali.kiali-operator.v1.41.0.yaml
.github/workflows/quay.io.kiali.kiali.v1.41.0.yaml
quay.io/kiali/kiali-operator/v1.41.0/Dockerfile
quay.io/kiali/kiali/v1.41.0/Dockerfile

Add kiali & kiali-operator v1.41.0 images for istio 1.11 upgrade.
* Partially Resolves [CASM-3619](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3619)
* Future work required by [CASM-3619](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3619)
* `surtur`
With the v1.41.0 upstream kiali & kiali-operator images, verified that Kiali was running as expected showing the upgraded version string. Will be validated again with rebuilt images in a live environment.
- Was …

CASM-3619: add kiali v1.41.0 images

---

.github/workflows/docker.io.demisto.boto3py3.kubectl_v1_21_12_1.0.0.49259.yaml
docker.io/demisto/boto3py3/kubectl_v1_21_12_1.0.0.49259/Dockerfile

Update boto3 image, include aws cli for use of sync
* Resolves [CASMPET-6182](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6182)
vshasta
verified with aws sync:
```
/snapshots/cray-bos-bitnami-etcd # ls
cray-bos_etcd_migration.snapshot.db  db-2023-02-22_21-00                  db-2023-02-24_22-00
db-2023-02-22_00-00                  db-2023-02-22_22-00                  db-2023-02-24_23-00
db-2023-02-22_01-00                  db-2023-02-22_23-00                  db-2023-02-25_00-00
db-2023-02-22_02-00                  db-2023-02-23_00-00                  db-2023-02-25_01-00
db-2023-02-22_16-00                  db-2023-02-23_01-00                  db-2023-02-27_15-00
db-2023-02-22_17-00                  db-2023-02-24_00-00                  db-2023-02-27_16-00 …
```

New boto3 image with updated aws cli

---

registry.opensource.zalan.do/acid/spilo-14/2.1-p7/Dockerfile
registry.opensource.zalan.do/acid/spilo-14/2.1-p7/pgq_ticker.ini

With the latest nightly rebuild of the spilo-14.2.1-p7 image, the pgqd package was updated from 3.3-5 to 3.5.1.
That change resulted in deprecation of some of the config values in the /home/postgres/pgq_ticker.ini file.
This fix overwrites the pgq_ticker.ini file in the postgres container due to change in pgqd:3.5-1.
This fix will allow for the image ([spilo-14.2.1-p7.yaml](https://github.com/Cray-HPE/container-images/actions/workflows/registry.opensource.zalan.do.acid.spilo-14.2.1-p7.yaml) to be rebuilt with all the latest packages such that the CSM 1.5 postgres clusters can then pick up the change.
* Resolves [CASMPET-6373](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET …

CAMSPET-6373 1.5 : Overwrite the pgq_ticker.ini file in the postgres container due to change in pgqd:3.5-1 in spilo-14

---

registry.opensource.zalan.do/acid/spilo-12/1.6-p3/Dockerfile
registry.opensource.zalan.do/acid/spilo-12/1.6-p3/pgq_ticker.ini

With the latest nightly rebuild of the spilo-12.1.6-p3 image, the pgqd package was updated from 3.3-5 to 3.5.1.
That change resulted in deprecation of some of the config values in the /home/postgres/pgq_ticker.ini file.
This fix overwrites the pgq_ticker.ini file in the postgres container due to change in pgqd:3.5-1.
This fix will allow for the image ([spilo-12.1.6-p3.yaml](https://github.com/Cray-HPE/container-images/actions/workflows/registry.opensource.zalan.do.acid.spilo-12.1.6-p3.yaml) to be rebuilt with all the latest packages such that the CSM 1.4 postgres clusters can then pick up the change.
* Resolves [CASMPET-6372](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET …

CASMPET-6372 1.4 : Overwrite the pgq_ticker.ini file in the postgres container due to change in pgqd:3.5-1 in spilo-12

---

.github/workflows/docker.io.coredns.coredns.1.9.3.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.11.6.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.0.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.2.yaml
.github/workflows/quay.io.cilium.hubble-relay.v1.12.4.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.11.6.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.0.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.2.yaml
.github/workflows/quay.io.cilium.operator-generic.v1.12.3.yaml

Some more cilium image builds started to fail after new vulnerabilities were added to the snyk database.   These are upstream images so I set the fail_on_snyk_error to false as recommended to suppress the error. 
* Resolves [CASMPET-6904](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6904)
Verified no failure in the branch build.

CASMPET-6409: Fix more snyk failures causing cilium build failures

---

.github/workflows/gcr.io.spiffe-io.oidc-discovery-provider.1.5.5.yaml
.github/workflows/gcr.io.spiffe-io.spire-agent.1.5.5.yaml
.github/workflows/gcr.io.spiffe-io.spire-server.1.5.5.yaml
gcr.io/spiffe-io/oidc-discovery-provider/1.5.5/Dockerfile
gcr.io/spiffe-io/spire-agent/1.5.5/Dockerfile
gcr.io/spiffe-io/spire-server/1.5.5/Dockerfile

This adds the spire images for 1.5.5. 1.6.0 has moved to a scratch base and is incompatible with the way we currently configure spire-server.

CASMPET-6421 Add spire 1.5.5 images

---

.github/workflows/cray-canu.canu-test.1.6.35.yaml
cray-canu/canu-test/Dockerfile
cray-canu/canu-test/file/entrypoint.sh

_CANU test logging docker image using CANU container image for red-green-light dashboard_
_https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-223_
* Resolves [CASMMON-223](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-223)
* Implementation will be done in `<cray-sysmgmt-health>` to use this image.
* `<gamora>`
* `<wasp>`
_Changes tested and success is verified._

CASMMON-223 Implement greenlight docker image using CANU container image

---

.github/workflows/quay.io.thanos.v0.31.0.yaml
quay.io/thanos/v0.31.0/Dockerfile

Push thanos image to the artifactory for thanos support for Prometheus scalability.
* Resolves -  https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-312
Gamora
ncn-m001:/mnt/developer/shreni # kubectl get pods -n sysmgmt-health
NAME                                                            READY   STATUS      RESTARTS   AGE
alertmanager-cray-sysmgmt-health-kube-p-alertmanager-0          2/2     Running     1          6m41s …

CASMMON-312: Push thanos image to the artifactory (container_images)

---

.github/workflows/docker.io.openpolicyagent.opa.0.52.0-envoy-rootless.yaml
docker.io/openpolicyagent/opa/0.52.0-envoy-rootless/Dockerfile

Add 0.52.0 version of OPA Envoy container (rootless). 
* Needed to complete [CASMPET-6321](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6321)
* Relates to https://github.com/Cray-HPE/cray-opa/pull/91
Tested build of dockerfile locally. 
None known

CASMPET-6321: Add OPA Envoy 0.52.0 Rootless Container

---

.github/workflows/docker.io.library.alpine.3.17.yaml
.github/workflows/docker.io.library.alpine.3.18.yaml
docker.io/library/alpine/3.17/Dockerfile
docker.io/library/alpine/3.18/Dockerfile

What do we need?
Alpine 3.17 and 3.18 images!
When do we need them?
Now!
(I just mimicked [the commit used to make the 3.16 image available](https://github.com/Cray-HPE/container-images/commit/445d2ffdc60965a37679261065ff07a1f3c08c1c))

Add Alpine 3.17 and 3.18 container images

---

ghcr.io/kyverno/kyverno/v1.7.5/Dockerfile
ghcr.io/kyverno/kyvernopre/v1.7.5/Dockerfile

Creating Dockerfile for Kyverno upgrade to v1.7.5.
Reference: https://jira-pro.it.hpe.com:8443/browse/CASMSEC-397

CASMSEC-397: Kyverno Upgrade Needed for N-2 Support Policy

---

.github/workflows/docker.io.jettech.kube-webhook-certgen.v1.3.0.yaml
docker.io/jettech/kube-webhook-certgen/v1.3.0/Dockerfile

cray-sysmgmt-health fails to install on k8s 1.22
[CASMTRIAGE-5496](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5496)
Implementation will be done in <cray-sysmgmt-health> to use this image
Tested on gamora

CASMTRIAGE-5496 cray-sysmgmt-health fails to install on k8s 1.22

---

.github/workflows/cray-canu.canu-test.1.6.36.yaml
cray-canu/canu-test-1.6.36/Dockerfile
cray-canu/canu-test-1.6.36/file/entrypoint.sh

_Switch password is shown in cleartext in multiple places in the log._
_Change in the image to remove the cleartext._
* Resolves [CASMMON-320](https://jira-pro.it.hpe.com:8443/browse/CASMMON-320)
* `<mug>`
- Was upgrade tested? Yes.

CASMMON-320 canu-test pod log should not have cleartext switch passwords

---

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r128.yaml
.github/workflows/docker.io.bitnami.etcd.3.5.9-debian-11-r15-patch.yaml
docker.io/bitnami/bitnami-shell/11-debian-11-r128/Dockerfile
docker.io/bitnami/etcd/3.5.9-debian-11-r15-patch/Dockerfile
docker.io/bitnami/etcd/3.5.9-debian-11-r15-patch/resources/libetcd.sh

New bitnami images, carrying patch to support cluster power off/on.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6642
Tested on ashton:
After simulating power off/on, cray-bos (with this fix) was the only one to start cleanly:
```
services         cray-bos-bitnami-etcd-0                                           2/2     Running                 2 (19m ago)       38m
services         cray-bos-bitnami-etcd-1                                           2/2     Running                 3 (3m45s ago)     38m
services         cray-bos-bitnami-etcd-2                                           2/2     Running                 2 (19m ago)       38m
services         cray-bos-bitnami-etcd-snapshotter-28122840-ld7fr                  0/2     Completed               0                 78m
services …
```

New version of bitnami etcd images, carrying one patch while we wait for upstream (CASMPET-6642)

---

.github/workflows/registry.k8s.io.metrics-server.metrics-server.v0.6.3.yaml
registry.k8s.io/metrics-server/metrics-server/v0.6.3/Dockerfile

New metric-server image for K8S 1.22
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6639
Tested on ashton:
```
pit:~ # helm history -n kube-system cray-metrics-server
REVISION	UPDATED                 	STATUS    	CHART                    	APP VERSION	DESCRIPTION
1       	Sun Jun 25 14:37:38 2023	superseded	cray-metrics-server-0.4.1	v0.3.6     	Install complete
2       	Wed Jun 28 17:23:51 2023	deployed  	cray-metrics-server-0.5.0	v0.6.3     	Upgrade complete
```
```
pit:~/brad # kubectl logs -n kube-system metrics-server-86bff57b87-cw2j4
I0628 17:30:26.279095       1 serving.go:342] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I0628 17:30:27.616407       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0628 17:30:27.616441       1 …
```

Add newer version of metric-server for K8S 1.22 (CASMPET-6639)

---

.github/workflows/docker.io.bitnami.external-dns.0.13.5.yaml
docker.io/bitnami/external-dns/0.13.5/Dockerfile

Add bitnami external-dns latest image 0.13.5 for CVE remediation.
* Resolves [CASMPET-6554](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6554)
To be tested on a CSM 1.5 system after the container image is created.
- Were new tests (or test …

CASMPET-6554: add external-dns 0.13.5 image

---

.github/workflows/docker.io.demisto.boto3py3.pet-utils-csm-1.6.yaml
docker.io/demisto/boto3py3/pet-utils-csm-1.6/Dockerfile

New util image with boto3, kubectl and awscli
* CASMPET-6758: update bitnami-etcd container with upstream merge
beau:
```
pit:~/brad # kubectl get pod/cray-etcd-test-etcd-post-install-nqpd4 -n services -o yaml | grep demis
image: artifactory.algol60.net/csm-docker/stable/docker.io/demisto/boto3py3:pet-utils-csm-1.6
```
```
pit:~/brad # kubectl logs pod/cray-etcd-test-etcd-post-install-nqpd4 -n services
Patching snapshotter cronjob to remove labels to allow scheduling alongside etcd pods..
cronjob.batch/cray-etcd-test-bitnami-etcd-snapshotter patched
cronjob.batch/cray-etcd-test-bitnami-etcd-snapshotter patched
Grabbing keys and S3 endpoint from etcd-backup-s3-credentials...
Download snapshot cray-etcd-test_etcd_migration.snapshot-1.db from http://rgw-vip.nmn... …
```

New pet-util image for 1.6 -- new boto3/kubectl/awscli

---

docker.io/zeromq/zeromq/v4.0.5/Dockerfile

Container rebuild for `zeromq:4.0.5` was broken for almost 2 years due to ZeroMQ source code download URL. This change adopts source code URL change, preserving version of `zeromq`.
* Resolves [CASMPET-6987](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6987)
* Github workflow
Github workflow is happy now. This image is used to run `curve_keygen` utility in [shasta-cfg](https://github.com/Cray-HPE/shasta-cfg/blob/release/1.6/utils/generators/zmq_curve#L70). Built image locally and ensured it provided similar functionality as the old one:
$ docker run -it --rm artifactory.algol60.net/csm-docker/stable/docker.io/zeromq/zeromq:v4.0.5 curve_keygen
This tool generates a CurveZMQ keypair, as two printable strings you can
use in configuration files or source …

CASMPET-6987 Fix zeromq build

---

.github/workflows/ghcr.io.aquasecurity.trivy-operator.0.21.1.yaml
ghcr.io/aquasecurity/trivy-operator/0.21.1/Dockerfile

Harden Kubernetes against CIS Benchmark (Control Plane).
Evaluating latest version of trivy-operator. Require the images from upstream, hence creating this PR.

CASMSEC-406: Harden Kubernetes against CIS Benchmark (Control Plane)

---

.github/workflows/quay.io.strimzi.kafka-bridge.0.28.0.yaml
.github/workflows/quay.io.strimzi.kafka.0.41.0-noJSM-chainsaw-kafka-3.6.0.yaml
.github/workflows/quay.io.strimzi.kafka.0.41.0-noJSM-chainsaw-kafka-3.6.1.yaml
.github/workflows/quay.io.strimzi.kafka.0.41.0-noJSM-chainsaw-kafka-3.6.2.yaml
.github/workflows/quay.io.strimzi.kafka.0.41.0-noJSM-chainsaw-kafka-3.7.0.yaml
.github/workflows/quay.io.strimzi.operator.0.41.0.yaml
images.mk
quay.io/strimzi/kafka-bridge/0.28.0/Dockerfile
quay.io/strimzi/kafka/0.41.0-noJSM-chainsaw-kafka-3.6.0/Dockerfile
quay.io/strimzi/kafka/0.41.0-noJSM-chainsaw-kafka-3.6.1/Dockerfile
quay.io/strimzi/kafka/0.41.0-noJSM-chainsaw-kafka-3.6.2/Dockerfile
quay.io/strimzi/kafka/0.41.0-noJSM-chainsaw-kafka-3.7.0/Dockerfile
quay.io/strimzi/operator/0.41.0/Dockerfile

Adding a container images for Strimzi kafka-operator 0.41.0 and related kafka (3.6.0, 3.6.1, 3.6.2, 3.7.0) and kafka-bridge(0.28.0) images for upgrading in CSM 1.6.
Note - Commenting out the mitigations for log4j vulnerabilities since the latest version of Kafka is using reload4j instead of log4j (Ref - https://kafka.apache.org/36/documentation.html#upgrade_320_notable)
* Resolves [CASMPET-6936](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6936)

CASMPET-6936 Adding images for strimzi kafka 0.41.0

---

.github/workflows/ghcr.io.aquasecurity.trivy-operator.0.21.3.yaml
ghcr.io/aquasecurity/trivy-operator/0.21.3/Dockerfile

Harden Kubernetes against CIS Benchmark (Control Plane).
Evaluating latest version of trivy-operator. Require the images from upstream, hence creating this PR.

CASMSEC-406-1: Harden Kubernetes against CIS Benchmark (Control Plane)

---

.github/workflows/quay.io.kiali.kiali-operator.v1.75.0.yaml
.github/workflows/quay.io.kiali.kiali.v1.75.0.yaml
quay.io/kiali/kiali-operator/v1.75.0/Dockerfile
quay.io/kiali/kiali/v1.75.0/Dockerfile

Add kiali & kiali-operator v1.75.0 images for istio 1.19.10 upgrade.
Part of EPIC CASMPET-6721: Upgrade istio to support k8s 1.24
* Resolves [CASMPET-6960](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6960)
* Future work required by [CASMPET-6721](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6721)
* `starlord`
* Craystack VM
With the v1.75.0 upstream kiali & kiali-operator images, verified that Kiali was running as expected showing the upgraded version string. Will be validated again with rebuilt images in a live environment.
- Were the install/upgrade-based validation checks/tests run (goss …

CASMPET-6960: Add kiali v1.75.0 images

---

.github/workflows/docker.io.bitnami.kubectl.1.26.4.yaml
docker.io/bitnami/kubectl/1.26.4/Dockerfile

Evaluating Kyverno chart upgrade which is needed for CSM version 1.6.x to support N-2 policy.
Require kubectl image as part of 1.10.7 version of Kyverno chart

CASMSEC-475: Kyverno chart upgrade needed for CSM version 1.6.x

---

docker.io/alpine/git/2.32.0/Dockerfile

OpenSSH daemon usage: remove sshd server package as it is unused
Is this change backwards compatible: yes, This is backwards compatible bugfix
* Resolves : https://jira-pro.it.hpe.com:8443/browse/CASMSEC-490
* `Starlord`
No

Casmsec 490

---

.github/workflows/github.com.kubernetes-sigs.cri-tools.v1.24.2.yaml
github.com/kubernetes-sigs/cri-tools/v1.24.2/Dockerfile

Create github.com/kubernetes-sigs/cri-tools/v1.24.2/Dockerfile. This creates a container image with 'crictl' which can be used for cray-preached-images and cray-drydock.
This container image is necessary in CSM 1.6 because in the K8s 1.24/SLES 15 SP6 build, cray-precache-images no longer works. The cray-precached-images container is not able to access the crictl binary on the host. This container image means that the cray-precached-images container won't need to access the crictl on the host.
* Resolves [CASMPET-7912](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7912)
* Resolves [CASMTRIAGE-7227](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7227)
* Fanta with SP6 and k8s 1.24
Upgraded the cray-precached-images chart and …

CASMPET-7912 add github.com/kubernetes-sigs/cri-tools/v1.24.2/Dockerfile

---

.github/workflows/docker.io.bitnami.kubectl.1.31.0.yaml
docker.io/bitnami/kubectl/1.31.0/Dockerfile

Kyverno chart upgrade which is needed for CSM version 1.6.x to support N-2 policy.
Ref: CASMSEC-475
Require bitnami kubectl image as part of 1.10.7 version of Kyverno chart. Hence we had used bitnami kubectl 1.26.4 version which has vulnerabilities (snyk report is pointing this). 
Through this PR we are using the latest bitnami kubectl 1.31.0 version.

CASMSEC-499 : Fix CVEs in artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/kubectl:1.26.4

---

docker.io/openpolicyagent/opa/0.52.0-envoy-rootless/Dockerfile
docker.io/openpolicyagent/opa/0.62.0-envoy-rootless/Dockerfile

This changeset updates the Open Policy Agent Envoy plugin images, 0.52.0 and 0.62.0, to build from `chainguard/glibc-dynamic` as a base instead of `chainguard/cc-dynamic`, as [cc-dynamic is no longer publicly available](https://support.chainguard.dev/hc/en-us/articles/28452542784667-Customer-Notice-Free-Image-Tier-Changes). [glibc-dynamic](https://console.chainguard.dev/org/hpe.com/images/public/image/glibc-dynamic/sbom) includes all of the same packages as [cc-dynamic](https://console.chainguard.dev/org/hpe.com/images/public/image/cc-dynamic/sbom), with the addition of `libstdc++`.
The branch-specific GitHub Actions that run to build both of these images have both completed successfully: [0.52.0](https://github.com/Cray-HPE/container-images/actions/runs/12203631898), …

CASMPET-7292: Fix OPA Envoy plugin base images

---

quay.io/cephcsi/cephcsi/v3.6.2/Dockerfile

The container image builds had broken for `quay.io/cephcsi/cephcsi/v3.6.2`. This PR updates the Dockerfile so that the container image builds successfully.
* Resolves [CASMPET-7296](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7296)
* Beau (vShasta2)
I used the new container image that was build in the k8s ceph-csi-cephfs and ceph-csi-rbd pods. I then created a PVC which uses ceph-csi-rbd and a PVC which uses ceph-csi-cephfs. The PVC were created successfully and pods were able to attach to the PVCs.
Low risk

CASMPET-7296 fix docker build for image quay.io/cephcsi/cephcsi/v3.6.2

---

quay.io/ceph/ceph/v17.2.6/Dockerfile

The container image builds had broken for quay.io/ceph/ceph/v17.2.6. This PR updates the Dockerfile so that the container image builds successfully.
* Resolves [CASMPET-7295](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7295)
* Beau (vshasta2)
I updated ceph so that all ceph daemons used the new container image. I successfully created PVC and wrote data to them. Ceph worked properly with the new container image.
Low risk

CASMPET-7295 update quay.io/ceph/ceph/v17.2.6/Dockerfile to fix container image build

---

.github/workflows/docker.io.library.alpine.3.19.yaml
.github/workflows/docker.io.library.alpine.3.20.yaml
.github/workflows/docker.io.library.alpine.3.21.yaml
README.md
docker.io/library/alpine/3.19/Dockerfile
docker.io/library/alpine/3.20/Dockerfile
docker.io/library/alpine/3.21/Dockerfile

Add Alpine 3.19, 3.20, and 3.21 container images.  Alpine 3.19 is needed for CASMHMS-6282 but while I'm doing that might as well add 3.20 and 3.21 as well.
* Resolves [CASMHMS-6282](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6282)
No testing other than the jobs that run as part of the build and PR

CASMHMS-6282: Add Alpine 3.19, 3.20, and 3.21 container images

---

.github/workflows/quay.io.cephcsi.cephcsi.v3.13.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-attacher.v4.4.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-node-driver-registrar.v2.9.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-provisioner.v3.6.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-resizer.v1.9.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-snapshotter.v6.2.1.yaml
quay.io/cephcsi/cephcsi/v3.13.0/Dockerfile
registry.k8s.io/sig-storage/csi-attacher/v4.4.0/Dockerfile
registry.k8s.io/sig-storage/csi-node-driver-registrar/v2.9.0/Dockerfile
registry.k8s.io/sig-storage/csi-provisioner/v3.6.0/Dockerfile
registry.k8s.io/sig-storage/csi-resizer/v1.9.0/Dockerfile
registry.k8s.io/sig-storage/csi-snapshotter/v6.2.1/Dockerfile

Pull new container images for ceph-csi in CSM 1.7.0.
* Resolves [CASMPET-7299](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7299)
* I have not tested the container images yet. I will be testing them in cray-ceph-csi-rbd and cray-ceph-csi-cephfs charts. I cannot test these charts on k8s 1.24 since they will not work on this k8s version.
Low risk.

CASMPET-7299 add ceph-csi container images for CSM 1.7

---

.github/workflows/ghcr.io.kyverno.background-controller.v1.13.2.yaml
.github/workflows/ghcr.io.kyverno.cleanup-controller.v1.13.2.yaml
.github/workflows/ghcr.io.kyverno.kyverno-cli.v1.13.2.yaml
.github/workflows/ghcr.io.kyverno.kyverno.v1.13.2.yaml
.github/workflows/ghcr.io.kyverno.kyvernopre.v1.13.2.yaml
.github/workflows/ghcr.io.kyverno.reports-controller.v1.13.2.yaml
ghcr.io/kyverno/background-controller/v1.13.2/Dockerfile
ghcr.io/kyverno/cleanup-controller/v1.13.2/Dockerfile
ghcr.io/kyverno/kyverno-cli/v1.13.2/Dockerfile
ghcr.io/kyverno/kyverno/v1.13.2/Dockerfile
ghcr.io/kyverno/kyvernopre/v1.13.2/Dockerfile
ghcr.io/kyverno/reports-controller/v1.13.2/Dockerfile

Evaluating Kyverno chart upgrade to version 1.13.2 which is required for CSM version 1.7.0 to support N-2 policy.

CASMSEC-504: Kyverno Upgrade Needed to support N-2 Policy

---

.github/workflows/docker.io.bitnami.external-dns.0.15.0.yaml
docker.io/bitnami/external-dns/0.15.0/Dockerfile

Add external-dns v0.15.0 image for use in CSM 1.7.
* Related to [CASM-5240](https://jira-pro.it.hpe.com:8443/browse/CASM-5240)
* [Chart update PR](https://github.com/Cray-HPE/cray-externaldns/pull/6)
* Beau
* Mug
* Tested deleting an external-dns domain and then ensuring that it gets recreated
* example below:
```
ncn-m001:~/mcdonald/cray-externaldns # kubectl get pods -A | grep external-dns
services         cray-externaldns-external-dns-5dfdc8b956-pzx7f                    1/1     Running                  0                   31s
ncn-m001:~/mcdonald/cray-externaldns # kubectl describe pod cray-externaldns-external-dns-5dfdc8b956-pzx7f -n services | grep Image
Image:         artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/external-dns:0.15.0
ncn-m001:~/mcdonald/cray-externaldns …
```

CASM-5240: Add image for external-dns v0.15.0

---

.github/workflows/docker.io.library.alpine.3.21.yaml
README.md

We need an arm64 Alpine 3.21 image to support building on Apple ARM laptops.
* Resolves [CASMHMS-5678](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-5678)
No testing required outside of pipeline build tests

CASMHMS-5678: Create arm64 Alpine 3.21 image

---

.github/workflows/quay.io.jetstack.cert-manager-cainjector.v1.17.0.yaml
.github/workflows/quay.io.jetstack.cert-manager-controller.v1.17.0.yaml
.github/workflows/quay.io.jetstack.cert-manager-startupapicheck.v1.17.0.yaml
.github/workflows/quay.io.jetstack.cert-manager-webhook.v1.17.0.yaml
quay.io/jetstack/cert-manager-cainjector/v1.17.0/Dockerfile
quay.io/jetstack/cert-manager-controller/v1.17.0/Dockerfile
quay.io/jetstack/cert-manager-startupapicheck/v1.17.0/Dockerfile
quay.io/jetstack/cert-manager-webhook/v1.17.0/Dockerfile

Add cert-manager v1.17.0 image for upgrading in CSM 1.7.
* Backing issue [CASMPET-7368](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7368)
* Corresponding [chart PR](https://github.com/Cray-HPE/cray-certmanager/pull/20)
To validate correctness I tested with this certificate:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: cert-manager
spec:
  dnsNames:
  - example.com
  secretName: test-cert-tls
  issuerRef:
    name: test-selfsigned-issuer
    kind: Issuer
```
And got this status after running `kubectl apply -f test-cert.yaml` and `kubectl describe certificate test-cert -n cert-manager`:
```
Status:
  Conditions:
    Last Transition Time:        2025-02-03T21:47:18Z
    Message:                     Issuing certificate as Secret does not …
```

CASMPET-7368: Add images for cert-manager v1.17.0

---

.github/workflows/ghcr.io.zalando.spilo-15.3.0-p1.yaml
.github/workflows/registry.opensource.zalan.do.acid.logical-backup.v1.10.1.yaml
.github/workflows/registry.opensource.zalan.do.acid.pgbouncer.master-27.yaml
.github/workflows/registry.opensource.zalan.do.acid.postgres-operator.v1.10.1.yaml
ghcr.io/zalando/spilo-15/3.0-p1/Dockerfile
ghcr.io/zalando/spilo-15/3.0-p1/pgq_ticker.ini
registry.opensource.zalan.do/acid/logical-backup/v1.10.1/Dockerfile
registry.opensource.zalan.do/acid/pgbouncer/master-27/Dockerfile
registry.opensource.zalan.do/acid/postgres-operator/v1.10.1/Dockerfile

Add the following container images for cray-postgres-operator upgrade to 1.10.1 in CSM 1.7
ghcr.io/zalando/spilo-15:3.0-p1
registry.opensource.zalan.do/acid/pgbouncer:master-27
registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
registry.opensource.zalan.do/acid/logical-backup:v1.10.1
* Resolves [CASMPET-7367](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7367)
* Beau
Upgrade the cray-postgres-operator chart on Beau and made sure that it worked correctly with the new images.
NA

CASMPET-7367 add container images for postgres-operator upgrade to 1.10.1

---

.github/workflows/ghcr.io.bank-vaults.vault-operator.v1.22.5.yaml
ghcr.io/bank-vaults/vault-operator/v1.22.5/Dockerfile

Add vault operator latest v1.22.5 image. Previously. I had merged https://github.com/Cray-HPE/container-images/pull/652, but that was a mistake by me, where I did not realize at the time that the repository the image was hosted on had changed, so that image is outdated. This is the correct image. 
* Part of [CASM-5241](https://jira-pro.it.hpe.com:8443/browse/CASM-5241)
```
Image:         artifactory.algol60.net/csm-docker/stable/ghcr.io/bank-vaults/vault-operator:v1.22.5
```
Low risk

CASM-5241: Add image for vault-operator v1.22.5

---

.github/workflows/quay.io.strimzi.kafka-bridge.0.31.1.yaml
.github/workflows/quay.io.strimzi.kafka.0.45.0-kafka-3.8.0.yaml
.github/workflows/quay.io.strimzi.kafka.0.45.0-kafka-3.8.1.yaml
.github/workflows/quay.io.strimzi.kafka.0.45.0-kafka-3.9.0.yaml
.github/workflows/quay.io.strimzi.operator.0.45.0.yaml
quay.io/strimzi/kafka-bridge/0.31.1/Dockerfile
quay.io/strimzi/kafka/0.45.0-kafka-3.8.0/Dockerfile
quay.io/strimzi/kafka/0.45.0-kafka-3.8.1/Dockerfile
quay.io/strimzi/kafka/0.45.0-kafka-3.9.0/Dockerfile
quay.io/strimzi/operator/0.45.0/Dockerfile

Add strimzi-kafka-operator v0.45.0 image for use in upgrade for CSM 1.7.
* Related to [CASMPET-7382](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7382)
* Chart PR: https://github.com/Cray-HPE/cray-kafka-operator/pull/10
* Shared kafka PR: https://github.com/Cray-HPE/cray-shared-kafka/pull/13
Previous image:
```
Image:      artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/operator:0.41.0
Image:      artifactory.algol60.net/csm-docker/stable/quay.io/strimzi/operator:0.41.0
kafkabridges.kafka.strimzi.io                         2025-02-06T21:00:26Z
kafkaconnectors.kafka.strimzi.io                      2025-02-06T21:00:26Z
kafkaconnects.kafka.strimzi.io                        2025-02-06T21:00:26Z
kafkamirrormaker2s.kafka.strimzi.io …
```

CASMPET-7382: Add strimzi-kafka-operator v0.45.0 for CSM 1.7

---

.github/workflows/registry.k8s.io.coredns.coredns.v1.11.4.yaml
.github/workflows/registry.k8s.io.kube-apiserver.v1.32.2.yaml
.github/workflows/registry.k8s.io.kube-controller-manager.v1.32.2.yaml
.github/workflows/registry.k8s.io.kube-proxy.v1.32.2.yaml
.github/workflows/registry.k8s.io.kube-scheduler.v1.32.2.yaml
registry.k8s.io/coredns/coredns/v1.11.4/Dockerfile
registry.k8s.io/kube-apiserver/v1.32.2/Dockerfile
registry.k8s.io/kube-controller-manager/v1.32.2/Dockerfile
registry.k8s.io/kube-proxy/v1.32.2/Dockerfile
registry.k8s.io/kube-scheduler/v1.32.2/Dockerfile

Generating images for k8s 1.32.2:
- coredns v1.11.4
- kube-apiserver v1.32.2
- kube-controller-manager v1.32.2
- kube-porxy v1.32.2
- kube-scheduler v1.32.2
* Resolves [CASMPET-7334](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7334)

CASMPET-7334: Generate kube-* v1.32.2 images and update coredns to v1.11.4

---

ghcr.io/zalando/spilo-15/3.0-p1/Dockerfile

Kyverno policies need to be updated in CSM 1.7. Postgres is currently violating these policies because it is running as root. This PR changes the container image so that it runs as the postgres USER.
The postgres user already exists in the container image.
```text
docker run --platform linux/amd64 -it --rm --entrypoint=bash ghcr.io/zalando/spilo-15:3.0-p1 -c 'id postgres'
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)
```
Postgres pods successfully run as postgres user.
```text
ncn-m001:~/leliasen # kubectl exec -it -n argo cray-nls-postgres-0 -- /bin/sh
$ id
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)
```
All postgres health checks passed when postgres pods were running as postgres user.
```text
PASSED. All postgresql …
```

CASMPET-7394 edit spilo-15:3.0-p1 container image to run as postgres user

---

.github/workflows/registry.k8s.io.coredns.coredns.v1.10.1.yaml
.github/workflows/registry.k8s.io.kube-apiserver.v1.27.16.yaml
.github/workflows/registry.k8s.io.kube-apiserver.v1.30.10.yaml
.github/workflows/registry.k8s.io.kube-controller-manager.v1.27.16.yaml
.github/workflows/registry.k8s.io.kube-controller-manager.v1.30.10.yaml
.github/workflows/registry.k8s.io.kube-proxy.v1.27.16.yaml
.github/workflows/registry.k8s.io.kube-proxy.v1.30.10.yaml
.github/workflows/registry.k8s.io.kube-scheduler.v1.27.16.yaml
.github/workflows/registry.k8s.io.kube-scheduler.v1.30.10.yaml
.github/workflows/registry.k8s.io.pause.3.6.yaml
.github/workflows/registry.k8s.io.pause.3.8.yaml
registry.k8s.io/coredns/coredns/v1.10.1/Dockerfile
registry.k8s.io/kube-apiserver/v1.27.16/Dockerfile
registry.k8s.io/kube-apiserver/v1.30.10/Dockerfile
registry.k8s.io/kube-controller-manager/v1.27.16/Dockerfile
registry.k8s.io/kube-controller-manager/v1.30.10/Dockerfile
registry.k8s.io/kube-proxy/v1.27.16/Dockerfile
registry.k8s.io/kube-proxy/v1.30.10/Dockerfile
registry.k8s.io/kube-scheduler/v1.27.16/Dockerfile
registry.k8s.io/kube-scheduler/v1.30.10/Dockerfile
registry.k8s.io/pause/3.6/Dockerfile
registry.k8s.io/pause/3.8/Dockerfile

On the upgrade journey to K8s 1.32, there will most likely need to be a couple stops along the way.  Generating containers for K8s 1.27.16 and K8s 1.30.10 as they are most likely the hops we'll have to make.
* Resolves [CASMPET-7412](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7412)

CASMPET-7412: Add K8s images needed for upgrade hops of 1.27.16 and 1.30.10

---

.github/workflows/registry.k8s.io.autoscaling.vpa-admission-controller.1.3.0.yaml
.github/workflows/registry.k8s.io.autoscaling.vpa-recommender.1.3.0.yaml
.github/workflows/registry.k8s.io.autoscaling.vpa-updater.1.3.0.yaml
.github/workflows/registry.k8s.io.ingress-nginx.kube-webhook-certgen.v1.5.2.yaml
registry.k8s.io/autoscaling/vpa-admission-controller/1.3.0/Dockerfile
registry.k8s.io/autoscaling/vpa-recommender/1.3.0/Dockerfile
registry.k8s.io/autoscaling/vpa-updater/1.3.0/Dockerfile
registry.k8s.io/ingress-nginx/kube-webhook-certgen/v1.5.2/Dockerfile

With K8s 1.32, we need to update `cray-vpa` to use `vpa` 1.3.0 and `kube-webhook-certgen` v1.5.2.
CASMPET-7447: Generate version 1.3.0 containers for VPA components
* Add ingress-nginx/kube-webhook-certgen v1.5.2 for cray-vpa admission-controller
* Resolves [CASMPET-7447](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7447)
With `cray-vpa` using these new container version on `molly`, they are no longer in CLBO.
```
ncn-m001:~ # kubectl get pods -n services | grep cray-vpa
cray-vpa-recommender-658574c8f6-mhxr6                             2/2     Running     0                  62m
cray-vpa-updater-c445c7c85-ldhpk                                  2/2     Running     0                  18h
ncn-m001:~ #
ncn-m001:~ # kubectl get pods -n services cray-vpa-recommender-658574c8f6-mhxr6 -o yaml | …
```

CASMPET-7447: Generate version 1.3.0 containers for VPA components

---

.github/workflows/docker.io.library.bitnami.kubectl.1.28.yaml
docker.io/library/bitnami/kubectl/1.28/Dockerfile

The `cray-vpa` chart uses the VPA manifest from Fairwinds.  Some chart somewhere uses the `docker.io/library/bitnami/kubectl:1.28` image.  This causes CSM build to fail with:
```
2025-03-31T20:15:48.889Z] + skopeo-inspect docker://artifactory.algol60.net/csm-docker/stable/docker.io/library/bitnami/kubectl:1.28
[2025-03-31T20:15:48.889Z] time="2025-03-31T20:15:48Z" level=fatal msg="Error parsing image name \"docker://artifactory.algol60.net/csm-docker/stable/docker.io/library/bitnami/kubectl:1.28\": reading manifest 1.28 in artifactory.algol60.net/csm-docker/stable/docker.io/library/bitnami/kubectl: manifest unknown: The named manifest is not known to the registry."
[2025-03-31T20:15:48.889Z] parallel: This job failed:
[2025-03-31T20:15:48.889Z] ./inspect.sh 'bitnami/kubectl:1.28'
```
I …

CASMPET-7447: VPA charts use docker.io/library/bitnami/kubectl:1.28

---

.github/workflows/quay.io.arkmq-org.activemq-artemis-broker-init.2.0.2.yaml
.github/workflows/quay.io.arkmq-org.activemq-artemis-broker-kubernetes.2.0.3.yaml
.github/workflows/quay.io.arkmq-org.activemq-artemis-operator.2.0.2.yaml
quay.io/arkmq-org/activemq-artemis-broker-init/2.0.2/Dockerfile
quay.io/arkmq-org/activemq-artemis-broker-kubernetes/2.0.3/Dockerfile
quay.io/arkmq-org/activemq-artemis-operator/2.0.2/Dockerfile

This PR updates the MQTT broker images used for DVS node health. The update is necessary to pickup a CVE that was discovered in the 2.39.0 version of the MQTT broker.
CVE-2025-27427: Apache ActiveMQ Artemis: Address routing-type can be updated by user without the createAddress permission
Affected versions:
Apache ActiveMQ Artemis 2.0.0 through 2.39.0
Description:
A vulnerability exists in Apache ActiveMQ Artemis whereby a user with the createDurableQueue or createNonDurableQueue permission on an address can augment the routing-type supported by that address even if said user doesn't have the createAddress permission for that particular address. When combined with the send permission and automatic queue creation a user could successfully send a message with a routing-type not supported by …

USS-4434: Add Artemis 2.40.0 and operator images

---

.github/workflows/docker.io.portainer.kubectl-shell.2.27.0.yaml
docker.io/portainer/kubectl-shell/2.27.0/Dockerfile
images.mk

CASMTRIAGE-7927: Update portainer image  based on CSM 1.7 Kubernetes Version v1.32 and use latest cray-site-init version 1.36.8
* Resolves [CASMTRIAGE-7927](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7927)
* `wasp`
https://spiraplan-pro-ext.it.hpe.com/SpiraPlan/3714/TestCase/List.aspx …

CASMTRIAGE-7927: Update portainer image 

---

.github/workflows/docker.io.bitnami.kubectl.1.32.3.yaml
docker.io/bitnami/kubectl/1.32.3/Dockerfile

Fix CVE's in artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/kubectl:1.31.0
Critical vulnerability found in current version.
This is required for Kyverno.

CASMPET-7475: Fix CVE's in artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/kubectl:1.31.0

---

.github/workflows/docker.io.bitnami.etcd.3.5.21-debian-12-r1.yaml
.github/workflows/docker.io.bitnami.os-shell.12-debian-12-r40.yaml
docker.io/bitnami/etcd/3.5.21-debian-12-r1/Dockerfile
docker.io/bitnami/os-shell/12-debian-12-r40/Dockerfile

This PR pulls the following images
- docker.io/bitnami/etcd:3.5.21-debian-12-r1
- docker.io/bitnami/os-shell:12-debian-12-r40
These are necessary for the bitnami-etcd upgrade in CSM 1.7.0
* Resolves [CASMPET-7406](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7406)
* Relates to [CASMPET-7396](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7396)
* Relates to [CASMPET-7229](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7229)
* I have used these images with cray-etcd-test chart on vShasta
Low risk

CASMPET-7406 pull new container images for bitnami/etcd upgrade in CSM 1.7.0

---

.github/workflows/quay.io.cephcsi.cephcsi.v3.14.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-attacher.v4.8.1.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-node-driver-registrar.v2.13.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-provisioner.v5.2.0.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-resizer.v1.13.2.yaml
.github/workflows/registry.k8s.io.sig-storage.csi-snapshotter.v8.2.1.yaml
quay.io/cephcsi/cephcsi/v3.14.0/Dockerfile
registry.k8s.io/sig-storage/csi-attacher/v4.8.1/Dockerfile
registry.k8s.io/sig-storage/csi-node-driver-registrar/v2.13.0/Dockerfile
registry.k8s.io/sig-storage/csi-provisioner/v5.2.0/Dockerfile
registry.k8s.io/sig-storage/csi-resizer/v1.13.2/Dockerfile
registry.k8s.io/sig-storage/csi-snapshotter/v8.2.1/Dockerfile

Pull latest container images for cephcsi v3.14.0. 
* Resolves [CASMPET-7520](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7520)
I will test the container images after they are built and published.
- Were new tests (or test …

CASMPET-7520: add latest ceph-csi container images for CSM 1.7

---

.github/workflows/ghcr.io.kyverno.background-controller.v1.14.1.yaml
.github/workflows/ghcr.io.kyverno.cleanup-controller.v1.14.1.yaml
.github/workflows/ghcr.io.kyverno.kyverno-cli.v1.14.1.yaml
.github/workflows/ghcr.io.kyverno.kyverno.v1.14.1.yaml
.github/workflows/ghcr.io.kyverno.kyvernopre.v1.14.1.yaml
.github/workflows/ghcr.io.kyverno.reports-controller.v1.14.1.yaml
ghcr.io/kyverno/background-controller/v1.14.1/Dockerfile
ghcr.io/kyverno/cleanup-controller/v1.14.1/Dockerfile
ghcr.io/kyverno/kyverno-cli/v1.14.1/Dockerfile
ghcr.io/kyverno/kyverno/v1.14.1/Dockerfile
ghcr.io/kyverno/kyvernopre/v1.14.1/Dockerfile
ghcr.io/kyverno/reports-controller/v1.14.1/Dockerfile

Kyverno community has released latest version which is 1.14.1. This is required to be supported in CSM due to many fixes. Hence submitting this PR.

CASMSEC-511: Kyverno Upgrade Needed to support N-2 Policy

---

.github/workflows/registry.k8s.io.coredns.coredns.v1.11.1.yaml
registry.k8s.io/coredns/coredns/v1.11.1/Dockerfile

While manually upgrading K8s to version 1.29.15, `kubeadm upgrade plan` calls out `coredns` version v1.11.1.
```
Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT        TARGET
kubelet     6 x v1.28.15   v1.29.15
Upgrade to the latest stable version:
COMPONENT                 CURRENT    TARGET
kube-apiserver            v1.28.15   v1.29.15
kube-controller-manager   v1.28.15   v1.29.15
kube-scheduler            v1.28.15   v1.29.15
kube-proxy                v1.28.15   v1.29.15
CoreDNS                   v1.10.1    v1.11.1
```
* Relates to [CASMPET-7512](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7512)
This is being tested on the vShasta system `molly`.
- [x ] Version number(s) incremented, if applicable
- …

CASMPET-7512: K8s 1.29 wants coredns v1.11.1

---

.github/workflows/docker.io.bitnami.kubectl.1.33.1.yaml
docker.io/bitnami/kubectl/1.33.1/Dockerfile

There is a critical vulnerability in current version of bitnami kubectl hence submitting this change to pull latest version.

CASMSEC-564: Fix CVE's in artifactory.algol60.net/csm-docker/stable/docker.io/bitnami/kubectl:1.32.3

---

.github/workflows/registry.k8s.io.kube-apiserver.v1.32.5.yaml
.github/workflows/registry.k8s.io.kube-controller-manager.v1.32.5.yaml
.github/workflows/registry.k8s.io.kube-proxy.v1.32.5.yaml
.github/workflows/registry.k8s.io.kube-scheduler.v1.32.5.yaml
registry.k8s.io/kube-apiserver/v1.32.5/Dockerfile
registry.k8s.io/kube-controller-manager/v1.32.5/Dockerfile
registry.k8s.io/kube-proxy/v1.32.5/Dockerfile
registry.k8s.io/kube-scheduler/v1.32.5/Dockerfile

Add Kubernetes 1.32.5 components.
* Resolves [CASMPET-7558](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7558).

CASMPET-7558: Add Kubernetes 1.32.5 components.

---

.github/workflows/quay.io.kiali.kiali-operator.v2.10.0.yaml
.github/workflows/quay.io.kiali.kiali.v2.10.0.yaml
quay.io/kiali/kiali-operator/v2.10.0/Dockerfile
quay.io/kiali/kiali/v2.10.0/Dockerfile

Add kiali-operator image v2.10.0 for upgrade in CSM 1.7.
* Related to [CASMPET-7376](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7376)
* Chart PR: https://github.com/Cray-HPE/cray-kiali/pull/15
Running the following script:
```
#!/bin/bash
kubectl get pods -n istio-system | grep kiali
kubectl port-forward svc/kiali -n istio-system 20001:20001 &
PORT_FORWARD_PID=$!
sleep 5
echo "Fetching Kiali metrics..."
curl -s http://localhost:20001/kiali/api/namespaces | head -c 50
echo ''
kill $PORT_FORWARD_PID
```
Resulted in the following output:
```
kiali-6fc596d955-779b6                                 1/1     Running   0          20h
Forwarding from 127.0.0.1:20001 -> 20001
Forwarding from [::1]:20001 -> 20001
Fetching Kiali metrics...
Handling connection for 20001 …
```

CASMPET-7376: Add kiali-operator image v2.10.0 for upgrade

---

.github/workflows/docker.io.bitnami.etcd.3.5.21-debian-12-r6.yaml
.github/workflows/docker.io.bitnami.os-shell.12-debian-12-r49.yaml
docker.io/bitnami/etcd/3.5.21-debian-12-r6/Dockerfile
docker.io/bitnami/os-shell/12-debian-12-r49/Dockerfile

Pull the latest bitnami etcd 3.5.x debian-12 images for reduced CVEs.
* Resolves [CASMPET-7548](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7548) and [CASMPET-7605](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7605)
- Was upgrade tested? …

CASMPET-7548: pull the latest bitnami etcd 3.5.x images

---

.github/workflows/quay.io.cephcsi.cephcsi.v3.14.2.yaml
quay.io/cephcsi/cephcsi/v3.14.2/Dockerfile

This PR adds cephcsi v3.14.2 image, which has less CVE counts compared with v3.14.0 image.
* Resolves [CASMPET-7600](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7600)
It will be tested after the new container image is generated.
_Are there known issues with …

CASMPET-7600: add cephcsi v3.14.2 image

---

.github/workflows/ghcr.io.zalando.spilo-15.3.2-p1.yaml
ghcr.io/zalando/spilo-15/3.2-p1/Dockerfile

CASMPET-7478: Upgrade to spilo-15:3.2-p1 for less CVEs
Create container image for `spilo-15:3.2-p1` to use with `cray-postgres-operator`.  It has less "High Severity" CVEs than `spilo-15:3.0-p1` which is what `cray-postgres-operator` uses now.
Cracked open `cray-postgres-operator` chart and used `spilo-15:3.2-p1` on `beau` to see if there were any obvious problems using the image.
```
pit:~/studenym/cray-postgres-operator/cray-postgres-operator # helm upgrade -n services cray-postgres-operator .
Release "cray-postgres-operator" has been upgraded. Happy Helming!
NAME: cray-postgres-operator
LAST DEPLOYED: Tue Sep  9 18:55:38 2025
NAMESPACE: services
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
To verify that postgres-operator has started, run:
kubectl --namespace=services get pods …
```

CASMPET-7478: Upgrade to spilo-15:3.2-p1 for less CVEs

---

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v4.2.2.yaml
ghcr.io/k8snetworkplumbingwg/multus-cni/v4.2.2/Dockerfile

CASMNET-2120: Add multus-cni v4.2.2
* Need to use thin_entrypoint; Copy COPY statements from multus-cni repo Dockerfile
* Image for [CASMNET-2120](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2120)
Was able to get this image to run on `beau` with changes to the `kube-multus-ds` daemonset.  The daemonset changes will need to be made in the `node-images` repo.
daemonset changes:
```
spec:
containers:
- args:
- --cni-conf-dir=/host/etc/cni/net.d
- --cni-bin-dir=/host/opt/cni/bin
- --multus-conf-file=/usr/src/multus-cni/images/00-multus.conf
- --cni-version=0.3.1
command:
- "/thin_entrypoint"
image: artifactory.algol60.net/csm-docker/stable/ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.2
<snip>
initContainers:
- command: ["/install_multus"]
args:
- "--type"
- "thin"
image: …
```

CASMNET-2120: Add multus-cni v4.2.2
