.github/workflows/quay.io.strimzi.kafka.0.15.0-kafka-2.2.1-noJSM-chainsaw.yaml, .github/workflows/quay.io.strimzi.kafka.0.15.0-kafka-2.3.1-noJSM-chainsaw.yaml, quay.io/strimzi/kafka/0.15.0-kafka-2.2.1-noJSM-chainsaw/Dockerfile, quay.io/strimzi/kafka/0.15.0-kafka-2.3.1-noJSM-chainsaw/Dockerfile
Fix/Mitigation for CVE-2022-2330[257]
CASM-2802: https://jira-pro.its.hpecorp.net:8443/browse/CASM-2802
CASM-2803: https://jira-pro.its.hpecorp.net:8443/browse/CASM-2803
NA
=> Fix/Mitigation for CVE-2022-2330[257] & CVE-2021-4104

.github/workflows/docker.io.curlimages.curl.7.81.0.yaml, docker.io/curlimages/curl/7.81.0/Dockerfile
This change adds the latest docker.io/curlimages/curl:7.81.0 
A snyk scan shows no issues with this image.
````
➜  7.81.0 snyk container test --docker curlimages/curl:7.81.0 --file=Dockerfile
Testing curlimages/curl:7.81.0...
Organization:      rnoska-hpe
Package manager:   apk
Target file:       Dockerfile
Project name:      docker-image|curlimages/curl
Docker image:      curlimages/curl:7.81.0
Platform:          linux/amd64
Base image:        docker.io/curlimages/curl:7.81.0
Licenses:          enabled
✓ Tested 21 dependencies for known issues, no vulnerable paths found. 
````
=> CASMINST-4081 Update to resolve known CVEs with 7.80.0.

.github/workflows/ghcr.io.kyverno.kyverno.v1.6.0.yaml, .github/workflows/ghcr.io.kyverno.kyvernopre.v1.6.0.yaml, ghcr.io/kyverno/kyverno/v1.6.0/Dockerfile, ghcr.io/kyverno/kyvernopre/v1.6.0/Dockerfile
CASMPET-5346: Adding workflow and Dockerfile for kyverno/kyvernopre images v1.6.0
* Resolves [CASMPET-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5346)
NA
=> CASMPET-5346: Adding workflow and Dockerfile for kyverno/kyvernopre images v1.6.0

.github/workflows/quay.io.strimzi.kafka.0.15.0-noJSM-chainsaw-kafka-2.2.1.yaml, .github/workflows/quay.io.strimzi.kafka.0.15.0-noJSM-chainsaw-kafka-2.3.0.yaml, .github/workflows/quay.io.strimzi.kafka.0.15.0-noJSM-chainsaw-kafka-2.3.1.yaml, .github/workflows/quay.io.strimzi.kafka.0.27.1-noJSM-chainsaw-kafka-2.8.0.yaml, .github/workflows/quay.io.strimzi.kafka.0.27.1-noJSM-chainsaw-kafka-2.8.1.yaml, .github/workflows/quay.io.strimzi.kafka.0.27.1-noJSM-chainsaw-kafka-3.0.0.yaml, .github/workflows/quay.io.strimzi.operator.0.27.1.yaml, quay.io/strimzi/kafka/0.15.0-noJSM-chainsaw-kafka-2.2.1/Dockerfile, quay.io/strimzi/kafka/0.15.0-noJSM-chainsaw-kafka-2.3.0/Dockerfile, quay.io/strimzi/kafka/0.15.0-noJSM-chainsaw-kafka-2.3.1/Dockerfile, quay.io/strimzi/kafka/0.27.1-noJSM-chainsaw-kafka-2.8.0/Dockerfile, quay.io/strimzi/kafka/0.27.1-noJSM-chainsaw-kafka-2.8.1/Dockerfile, quay.io/strimzi/kafka/0.27.1-noJSM-chainsaw-kafka-3.0.0/Dockerfile, quay.io/strimzi/operator/0.27.1/Dockerfile
- Add 0.27.1 strimzi images
- Add new names for 0.15.0 strimzi kafka images to work properly with strimzi operator
=> Casmpet 5362

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.8.1.yaml, ghcr.io/k8snetworkplumbingwg/multus-cni/v3.8.1/Dockerfile
Testing to see if this has better snyk scan results (and works with current k8s version).
* Resolves [CASMINST-4171](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4171)
N/A
N/A
N/A
Low
=> Bring in newer multus image from ghcr.io

.github/workflows/quay.io.ceph.ceph.v15.2.16.yaml, quay.io/ceph/ceph/v15.2.16/Dockerfile
This is built on a more recently patched centos:stream8
* Resolves CASMPET-5417
N/A
n/a
=> CASMPET-5417 - adding ceph v15.2.16

.github/workflows/quay.io.ceph.ceph-grafana.8.3.5.yaml, quay.io/ceph/ceph-grafana/8.3.5/Dockerfile
Adding latest ceph-grafana image
* Resolves CASMPET-5476
* craystack
n/a - not automatically deployed
=> CASMPET-5476 - adding latest ceph-grafana container image

.github/workflows/docker.io.library.alpine.3.15.yaml, docker.io/library/alpine/3.15/Dockerfile
Add alpine:3.15 to the library as a patched image.
* Resolves [CASMCMS-7764](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7764)
Just adding a new security patched base image.
=> Add alpine:3.15 to the library.

.github/workflows/gcr.io.k8s-staging-multitenancy.hnc-manager.v1.0.0.yaml, gcr.io/k8s-staging-multitenancy/hnc-manager/v1.0.0/Dockerfile
New hnc-manager v1.0.0 image
* Resolves [CASMINST-4299](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4299)
Will test via chart
Not yet
Not yet
Low
=> New hnc-manager v1.0.0 image

.github/workflows/docker.io.velero.velero-plugin-for-aws.v1.2.1.yaml, docker.io/velero/velero-plugin-for-aws/v1.2.1/Dockerfile
adding new version
* ResolvesCASMPET-5596
=> Adding new velero plugin for aws image

.github/workflows/docker.io.velero.velero-restic-restore-helper.v1.6.3.yaml, docker.io/velero/velero-restic-restore-helper/v1.6.3/Dockerfile
Adding new version
* Resolves CASMPET-5576
=> Adding newer version fo velero restic restore helper

.github/workflows/docker.io.velero.velero-plugin-for-aws.v1.3.1.yaml, .github/workflows/docker.io.velero.velero-restic-restore-helper.v1.7.1.yaml, docker.io/velero/velero-plugin-for-aws/v1.3.1/Dockerfile, docker.io/velero/velero-restic-restore-helper/v1.7.1/Dockerfile
adding in additional container images to support upgrade to velero 1.7.1
* Resolves CASMPET-5583
=> Adding velero 1.7.1 additional container images

.github/workflows/quay.io.ceph.ceph.v16.2.9.yaml, quay.io/ceph/ceph/v16.2.9/Dockerfile
ceph container image version bump
* Resolves CASMINST-4686
=> Adding latest version of the ceph container image

.github/workflows/gcr.io.spiffe-io.oidc-discovery-provider.1.3.0.yaml, .github/workflows/gcr.io.spiffe-io.spire-agent.1.3.0.yaml, .github/workflows/gcr.io.spiffe-io.spire-server.1.3.0.yaml, gcr.io/spiffe-io/oidc-discovery-provider/1.3.0/Dockerfile, gcr.io/spiffe-io/spire-agent/1.3.0/Dockerfile, gcr.io/spiffe-io/spire-server/1.3.0/Dockerfile
Add new Spire images in preparation for an upgrade.
CASMPET-5081
None yet, just needing to get the new images built and published.
None. These are not used yet.
=> CASMPET-5081 Update Spire images.

.github/workflows/ghcr.io.kyverno.kyverno.v1.6.2.yaml, .github/workflows/ghcr.io.kyverno.kyvernopre.v1.6.2.yaml, ghcr.io/kyverno/kyverno/v1.6.2/Dockerfile, ghcr.io/kyverno/kyvernopre/v1.6.2/Dockerfile
Adding Dockerfile and workflow for kyverno 1.6.2 version
=> Adding Dockerfile and workflow for kyverno 1.6.2 version

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.9.yaml, ghcr.io/k8snetworkplumbingwg/multus-cni/v3.9/Dockerfile
Bring in latest multus image to see if better snyk results
* Resolves [CASMPET-5821](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5821)
N/A
N/A
N/A
None
=> Bring in multus v3.9 (CASMPET-5821)

.github/workflows/registry.suse.com.suse.sle15.15.4.yaml, registry.suse.com/suse/sle15/15.4/Dockerfile
Add SLES 15.4
Verified the new image builds
* build pipeline
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
no
=> Add SLES 15.4

quay.io/cephcsi/cephcsi/v3.6.2/Dockerfile
=> CASMPET-5890 change Dockerfile to build ceph-csi after version bump

docker.io/portainer/kubectl-shell/latest-v1.21.1-amd64/Dockerfile
Apk update the upstream image in the dockerfile for security purposes.
* Resolves CASMPET-5802
Local testing against a k8s cluster
Validated apk upgraded packages from the base image, no functionality should change from this pr.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? no
- Were continuous integration tests run? If not, why? The entrypoint didn't change.
- Was …
=> CASMPET-5802: Apk upgrade portainer/kubectl-shell

.github/workflows/gcr.io.spiffe-io.oidc-discovery-provider.1.4.0.yaml, .github/workflows/gcr.io.spiffe-io.spire-agent.1.4.0.yaml, .github/workflows/gcr.io.spiffe-io.spire-server.1.4.0.yaml, gcr.io/spiffe-io/oidc-discovery-provider/1.4.0/Dockerfile, gcr.io/spiffe-io/spire-agent/1.4.0/Dockerfile, gcr.io/spiffe-io/spire-server/1.4.0/Dockerfile
Pull in the latest Spire versions. These are not used yet but will need to get into the container images project. 
* Partly resolves [CASMPET-5081](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5081)
These will be tested on VShasta once the images are published.
=> CASMPET-5081 Update Spire to 1.4.0

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.9.1.yaml, ghcr.io/k8snetworkplumbingwg/multus-cni/v3.9.1/Dockerfile
Build latest version of multus in CVE reduction attempt.
* Resolves [CASMPET-5821](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5821)
Not yet
Not yet
Will test before including in manifest
None
=> Begin building v3.9.1 of multus

munge-munge/1.1.3/Dockerfile
Updates the munge image to use sp4
* CASMCMS-8076
New image built successfully.
None
=> CASMCMS-8076: Update munge image to sp4

.github/workflows/docker.io.gitea.gitea.1.17.2-rootless.yaml
Adds the workflow needed to build the new gitea 1.17.2 image
* Related to CASMCMS-8251
=> CASMCMS-8251: Add workflow for gitea 1.17.2 image

.github/workflows/registry.opensource.zalan.do.acid.logical-backup.v1.8.0.yaml, .github/workflows/registry.opensource.zalan.do.acid.pgbouncer.master-22.yaml, .github/workflows/registry.opensource.zalan.do.acid.postgres-operator.v1.8.2.yaml, .github/workflows/registry.opensource.zalan.do.acid.spilo-14.2.1-p6.yaml, registry.opensource.zalan.do/acid/logical-backup/v1.8.0/Dockerfile, registry.opensource.zalan.do/acid/pgbouncer/master-22/Dockerfile, registry.opensource.zalan.do/acid/postgres-operator/v1.8.2/Dockerfile, registry.opensource.zalan.do/acid/spilo-14/2.1-p6/Dockerfile
New images for bringing in lastest upstream zalando operator.
* Resolves [CASMINST-5476](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5476)
Testing in progress
=> Add builds for new postgres-operator images

.github/workflows/quay.io.ceph.ceph.v17.2.5.yaml, quay.io/ceph/ceph/v17.2.5/Dockerfile
ceph version 17.2.5 container image
* Resolves CASMPET-6080
=> CASMPET-6080 - ceph version 17.2.5 container image

.github/workflows/quay.io.ceph.ceph.v17.yaml, .github/workflows/quay.io.prometheus.alertmanager.v0.24.0.yaml, .github/workflows/quay.io.prometheus.node-exporter.v1.4.0.yaml, .github/workflows/quay.io.prometheus.prometheus.v2.39.1.yaml, quay.io/ceph/ceph/v17/Dockerfile, quay.io/prometheus/alertmanager/v0.24.0/Dockerfile, quay.io/prometheus/node-exporter/v1.4.0/Dockerfile, quay.io/prometheus/prometheus/v2.39.1/Dockerfile
additional container image updates for the ceph upgrade
* Resolves CASMPET-6082
_How were the changes tested …
=> CASMPET-6082 - additional container image updates for the ceph upgrade

docker.io/alpine/helm/3.9.4/Dockerfile
adding docker
_How were the changes tested and success verified? If schema …
=> CASMPET-6102_patch - adding docker

docker.io/grafana/grafana/8.5.9/Dockerfile, docker.io/grafana/grafana/8.5.9/runBuildPrep.sh
Scope and Summary:
Added the Clusterview Grafana Panel to /var/lib/grafana/plugins.
JIRA Ticket:
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-233
Changes:
Add a pre-build script to clone the source code of the clusterview panel
Updated the dockerfile to build the plugin from the source code
Testing:
Grafana Startup
=> CASMMON-233 Cluster-view-panel

.github/workflows/docker.io.library.vault.1.12.1.yaml, .github/workflows/ghcr.io.banzaicloud.bank-vaults.1.16.0.yaml, .github/workflows/ghcr.io.banzaicloud.vault-operator.1.16.0.yaml, docker.io/library/vault/1.12.1/Dockerfile, ghcr.io/banzaicloud/bank-vaults/1.16.0/Dockerfile, ghcr.io/banzaicloud/vault-operator/1.16.0/Dockerfile
- Add vault 1.12.1
- Add bank-vaults 1.16.0
- Add vault-operator 1.16.0
=> CASMPET-6151 Add latest vault images

.github/workflows/quay.io.ceph.ceph.v17.2.3.yaml, quay.io/ceph/ceph/v17.2.3/Dockerfile
The latest RPM we have avaialble is 17.2.3, and our NCN images lock the quay and ceph package and image versions together.
N/A
* Resolves [MTL-1708](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1708)
_List the environments in which these …
=> MTL-1708 Make quay.io/ceph 17.2.3 image

.github/workflows/docker.io.rust.1.yaml, docker.io/rust/1/Dockerfile
- adding rust upstream image
CASMNET-1967
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?n
- Were continuous integration tests run? If not, why?n
- Was upgrade tested? If not, why?n
- Was …
=> feature/CASMNET-1967 - adding rust upstream image

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r54.yaml, .github/workflows/docker.io.bitnami.etcd.3.5.6-debian-11-r0.yaml, docker.io/bitnami/bitnami-shell/11-debian-11-r54/Dockerfile, docker.io/bitnami/etcd/3.5.6-debian-11-r0/Dockerfile
Needed for support of bitnami etcd helm chart.
* Resolves [CASMPET-6180](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6180)
Coming
Coming
=> Add bitnami etcd helm chart images (CASMPET-6180)

.github/workflows/registry.opensource.zalan.do.acid.spilo-14.2.1-p7.yaml, registry.opensource.zalan.do/acid/spilo-14/2.1-p7/Dockerfile
Locally build spilo-14:2.1-p7 to pickup recent fixes
This will be tested along with the postgres operator work that is in progress.
* Resolves [CASMPET-6197](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6197)
* Change will also be needed in NA
* Future work required by NA
* Documentation changes required in NA
* Merge with/before/after NA
This will be tested as part on the postgres-operator upgrade that is in progress
- Were continuous …
=> CASMPET-6197 : Pull in latest spilo-14 with fixes for timescaledb 2.7.2

.github/workflows/registry.opensource.zalan.do.acid.logical-backup.v1.8.2.yaml, registry.opensource.zalan.do/acid/logical-backup/v1.8.2/Dockerfile
Locally build logical-backup:v1.8.2 to pickup recent fixes
This will be tested along with the postgres operator work that is in progress.
* Resolves [CASMPET-6199](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6199)
* Change will also be needed in NA
* Future work required by NA
* Documentation changes required in NA
* Merge with/before/after NA
This will be tested as part on the postgres-operator upgrade that is in progress
- Were continuous …
=> CASMPET-6199 : Pull in latest logical-backup:v1.8.2

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r54.yaml, .github/workflows/docker.io.bitnami.etcd.3.5.6-debian-11-r0.yaml, .github/workflows/registry.opensource.zalan.do.acid.logical-backup.v1.8.0.yaml, .github/workflows/registry.opensource.zalan.do.acid.spilo-14.2.1-p6.yaml
These are upstream images so I set the fail_on_snyk_error to false as recommended to suppress the error. 
* Resolves [CASMPET-6186](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6186) partially
Verified on branch build.
=> Update fail_on_snyk_errors for upstream images

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r74.yaml, .github/workflows/docker.io.bitnami.etcd.3.5.7-debian-11-r0.yaml, docker.io/bitnami/bitnami-shell/11-debian-11-r74/Dockerfile, docker.io/bitnami/etcd/3.5.7-debian-11-r0/Dockerfile
Add latest binami etcd images
* Resolves [CASMPET-6186](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6186)
vshasta
Pulled upstream image
Low
=> Add latest binami etcd images

.github/workflows/gcr.io.spiffe-io.oidc-discovery-provider.1.5.4.yaml, .github/workflows/gcr.io.spiffe-io.spire-agent.1.5.4.yaml, .github/workflows/gcr.io.spiffe-io.spire-server.1.5.4.yaml, gcr.io/spiffe-io/oidc-discovery-provider/1.5.4/Dockerfile, gcr.io/spiffe-io/spire-agent/1.5.4/Dockerfile, gcr.io/spiffe-io/spire-server/1.5.4/Dockerfile
This adds the spire 1.5.4 images for use with the new cray-spire chart.
=> CASMPET-6279 Add spire 1.5.4 images

.github/workflows/ghcr.io.k8snetworkplumbingwg.multus-cni.v3.9.3.yaml, ghcr.io/k8snetworkplumbingwg/multus-cni/v3.9.3/Dockerfile
Bring in latest multus image for CVE remediation
* Resolves [CASMPET-5862](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5862)
Will test after merge
TBD
TBD
Low
=> Bring in latest multus image for CVE remediation

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r79.yaml, .github/workflows/docker.io.bitnami.etcd.3.5.7-debian-11-r4.yaml, docker.io/bitnami/bitnami-shell/11-debian-11-r79/Dockerfile, docker.io/bitnami/etcd/3.5.7-debian-11-r4/Dockerfile
Bring in newer docker images, and pre-create configuration directory for initial cluster config.
* Resolves [CASMPET-6186](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6186)
Basic testing on vshasta 
Chart installs/upgrades
Low
=> Updated bitnami etcd images

.github/workflows/docker.io.bitnami.etcd.3.5.7-debian-11-r0-patch.yaml, docker.io/bitnami/etcd/3.5.7-debian-11-r0-patch/Dockerfile, docker.io/bitnami/etcd/3.5.7-debian-11-r0-patch/resources/etcd-env.sh, docker.io/bitnami/etcd/3.5.7-debian-11-r0-patch/resources/snapshot.sh
We can go back to stock image once this merges:
https://github.com/bitnami/containers/pull/23347
Needed until we merge an upstream fix.
* Resolves [CASMPET-6182](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6182)
vshasta
Lots of chart installs/snapshots
Low
=> Add patched files until upstream merges PR

.github/workflows/docker.io.grafana.grafana.9.3.2.yaml, docker.io/grafana/grafana/9.3.2/Dockerfile
_Grafana Upgrade and Dashboard improvements by supporting new visualizations_
_Upgrades Grafana to 9.3.2 similar to HPCM and SMA_
* Resolves [CASM-3871](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3871)
* `frigg`
- Was upgrade tested? YES.
_No known issues with these changes and no special considerations._
=> CASM-3871 Grafana Upgrade and Dashboard improvements

.github/workflows/docker.io.bitnami.etcd.3.5.6-debian-11-r10-patch.yaml, docker.io/bitnami/etcd/3.5.6-debian-11-r10-patch/Dockerfile, docker.io/bitnami/etcd/3.5.6-debian-11-r10-patch/resources/libetcd.sh, docker.io/bitnami/etcd/3.5.6-debian-11-r10-patch/resources/snapshot.sh
Updated docker image now that our first upstream PR has merged.  Will push add'l PRs for patches being carried here once we're confident patches are final.
* Resolves [CASMPET-6182](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6182)
Smoke changes in vshasta.
Smoke changes in vshasta.
Low
=> Updated bitnami etcd docker image, carrying three remaining patches

.github/workflows/quay.io.argoproj.argocli.v3.4.5.yaml, .github/workflows/quay.io.argoproj.argoexec.v3.4.5.yaml, .github/workflows/quay.io.argoproj.workflow-controller.v3.4.5.yaml, quay.io/argoproj/argocli/v3.4.5/Dockerfile, quay.io/argoproj/argoexec/v3.4.5/Dockerfile, quay.io/argoproj/workflow-controller/v3.4.5/Dockerfile
Add the latest argo v3.4.5 images to pick up bug fixes.
* Resolves [CASM-3813](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3813)
To be tested after images are built by CSM.
Low.
=> CASM-3813: add argo v3.4.5 images

.github/workflows/quay.io.artemiscloud.activemq-artemis-broker-init.1.0.14.yaml, .github/workflows/quay.io.artemiscloud.activemq-artemis-broker-kubernetes.1.0.14.yaml, .github/workflows/quay.io.artemiscloud.activemq-artemis-operator.1.0.10.yaml, quay.io/artemiscloud/activemq-artemis-broker-init/1.0.14/Dockerfile, quay.io/artemiscloud/activemq-artemis-broker-kubernetes/1.0.14/Dockerfile, quay.io/artemiscloud/activemq-artemis-operator/1.0.10/Dockerfile
This adds the container images used by the dvs-mqtt ActiveMQ Artemis helm chart.
=> CASMPET-6393 Add ActiveMQ Artemis containers

.github/workflows/quay.io.artemiscloud.activemq-artemis-broker-kubernetes.1.0.14-cray1.yaml, quay.io/artemiscloud/activemq-artemis-broker-kubernetes/1.0.14-cray1/Dockerfile, quay.io/artemiscloud/activemq-artemis-broker-kubernetes/1.0.14-cray1/readinessProbe.sh
This adds a modified broker image for use with a HA live/backup AMQA cluster.
=> CASMPET-6363 Add modified AMQA Broker image

.github/workflows/ghcr.io.k3d-io.k3d-tools.5.4.9.yaml, ghcr.io/k3d-io/k3d-tools/5.4.9/Dockerfile
=> add k3d images

.github/workflows/docker.io.bitnami.bitnami-shell.11-debian-11-r109.yaml, .github/workflows/docker.io.bitnami.etcd.3.5.8-debian-11-r3.yaml, docker.io/bitnami/bitnami-shell/11-debian-11-r109/Dockerfile, docker.io/bitnami/etcd/3.5.8-debian-11-r3/Dockerfile
Bring in latest bitnami etcd images with upstream merges
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6504
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing
=> Consume upstream changes which have merged for bitnami etcd (CASMPET-6504)

.github/workflows/docker.io.metacontrollerio.metacontroller.v4.10.3.yaml, docker.io/metacontrollerio/metacontroller/v4.10.3/Dockerfile
Add metacontroller latest image (v4.10.3) for CVE remediation (only 1 low severity vulnerability).
* Resolves CASMPET-6235
* Change will also be needed in CSM V1.4.1
Will test it after the container image is generated.
- Were the …
=> CASMPET-6235: add metacontroller v4.10.3 image

quay.io/kiali/kiali/v1.36.7/Dockerfile, quay.io/kiali/kiali/v1.41.0/Dockerfile
=> use distroless image for kiali

ghcr.io/k8snetworkplumbingwg/multus-cni/v3.9.1/Dockerfile, ghcr.io/k8snetworkplumbingwg/multus-cni/v3.9.3/Dockerfile
in 3.9.3, upstream used this: https://github.com/k8snetworkplumbingwg/multus-cni/blob/v3.9.3/images/Dockerfile
judging by the [minimum changes](https://github.com/k8snetworkplumbingwg/multus-cni/compare/v3.9.1...v3.9.3) between, 3.9.1 to 3.9.3, i update both to use python:slim and added apt update.
CVE count is down from 914 to 52low
* Local …
=> CASMPET-6241 use a newer base image

.github/workflows/docker.io.bitnami.external-dns.0.13.4-debian-11-r14.yaml, docker.io/bitnami/external-dns/0.13.4-debian-11-r14/Dockerfile
Add the latest external-dns image for CVE remediation.
* Resolves CASMPET-6554
- …
=> CASMPET-6554: add latest external-dns image

.github/workflows/ghcr.io.kyverno.kyverno.v1.7.5.yaml, .github/workflows/ghcr.io.kyverno.kyvernopre.v1.7.5.yaml
Created new workflow files for Kyverno upgrade to v1.7.5 version.
Reference: https://jira-pro.it.hpe.com:8443/browse/CASMSEC-397
=> CASMSEC-397-1: Kyverno Upgrade Needed for N-2 Support Policy

docker.io/portainer/kubectl-shell/latest-v1.21.1-amd64/Dockerfile
=> CASMINST-6512 add csi binary to image instead of host mount

.github/workflows/ghcr.io.aquasecurity.trivy-operator.0.14.0.yaml, ghcr.io/aquasecurity/trivy-operator/0.14.0/Dockerfile
CIS Kubernetes Compliance Scan and Backlog Creation.
As part CIS Kubernetes compliance evaluation, evaluating trivy-operator tool. Hence need the public image in artifactory for installation on CSM systems.
=> CASM-3472: CIS Kubernetes Compliance Scan and Backlog Creation

.github/workflows/ghcr.io.kyverno.kyverno.v1.9.5.yaml, .github/workflows/ghcr.io.kyverno.kyvernopre.v1.9.5.yaml, ghcr.io/kyverno/kyverno/v1.9.5/Dockerfile, ghcr.io/kyverno/kyvernopre/v1.9.5/Dockefile
As part of this issue, we are planning to upgrade Kyverno to 1.9.5 version and for this we need images from public repository to be made available in artifactory.
=> CASMSEC-402: Kyverno chart needs to handle a large amount of change requests during CSM upgrade

docker.io/portainer/kubectl-shell/latest-v1.21.1-amd64/Dockerfile
=> CASMTRIAGE-5801 remove content in /tmp not the /tmp itself

.github/workflows/ghcr.io.kyverno.kyverno.v1.8.5.yaml, .github/workflows/ghcr.io.kyverno.kyvernopre.v1.8.5.yaml, ghcr.io/kyverno/kyverno/v1.8.5/Dockerfile, ghcr.io/kyverno/kyvernopre/v1.8.5/Dockerfile
As part of Kyverno upgrade submitting these changes. We have to upgrade to Kyverno version 1.8.5 before upgrading to version 1.9.5. Hence require these images to evaluate on CSM.
=> CASMSEC-402-2: Kyverno upgrade to handle large change requests 

.github/workflows/docker.io.bitnami.etcd.3.5.9-debian-11-r148.yaml, .github/workflows/docker.io.bitnami.os-shell.11-debian-11-r90.yaml, docker.io/bitnami/etcd/3.5.9-debian-11-r148/Dockerfile, docker.io/bitnami/os-shell/11-debian-11-r90/Dockerfile
=> Updated etcd container images for CSM 1.6 (CASMPET-6758)

.github/workflows/docker.io.demisto.boto3py3.pet-utils-csm-1.5.yaml, docker.io/demisto/boto3py3/pet-utils-csm-1.5/Dockerfile
=> Add updated CSM 1.5 boto3 utils image for DR

.github/workflows/docker.io.openpolicyagent.opa.0.62.0-envoy-rootless.yaml, docker.io/openpolicyagent/opa/0.62.0-envoy-rootless/Dockerfile
Add the latest OPA Envoy 0.62.0 image.
- Were …
=> Add OPA Envoy 0.62.0 Rootless Container

.github/workflows/docker.io.victoriametrics.operator.v0.35.1.yaml, .github/workflows/docker.io.victoriametrics.vmagent.v1.93.1.yaml, .github/workflows/docker.io.victoriametrics.vmalert.v1.93.1.yaml, .github/workflows/docker.io.victoriametrics.vminsert.v1.93.1-cluster.yaml, .github/workflows/docker.io.victoriametrics.vmselect.v1.93.1-cluster.yaml, .github/workflows/docker.io.victoriametrics.vmstorage.v1.93.1-cluster.yaml, .github/workflows/gcr.io.google_containers.hyperkube.v1.18.0.yaml, docker.io/victoriametrics/operator/v0.35.1/Dockerfile, docker.io/victoriametrics/vmagent/v1.93.1/Dockerfile, docker.io/victoriametrics/vmalert/v1.93.1/Dockerfile, docker.io/victoriametrics/vminsert/v1.93.1-cluster/Dockerfile, docker.io/victoriametrics/vmselect/v1.93.1-cluster/Dockerfile, docker.io/victoriametrics/vmstorage/v1.93.1-cluster/Dockerfile, gcr.io/google_containers/hyperkube/v1.18.0/Dockerfile
* Resolves -  https://jira-pro.it.hpe.com:8443/browse/CASMMON-399
Mug
=> CASMMON-399: Push all the images to the Arti

.github/workflows/docker.io.victoriametrics.vmalert.v1.102.0.yaml, .github/workflows/docker.io.victoriametrics.vminsert.v1.96.0-cluster.yaml, docker.io/victoriametrics/vmalert/v1.102.0/Dockerfile, docker.io/victoriametrics/vminsert/v1.96.0-cluster/Dockerfile
#
CASMMON-418 Fix CVEs for vmalert:v1.93.1 and CASMMON-421 vminsert:v1.93.1-cluster
https://jira-pro.it.hpe.com:8443/browse/CASMMON-417
https://jira-pro.it.hpe.com:8443/browse/CASMMON-421
Mug
=> CASMMON-418 Fix CVEs for vmalert:v1.93.1 and CASMMON-421 vminsert:v1.93.1-cluster

.github/workflows/quay.io.reactiveops.ci-images.v11-alpine.yaml, quay.io/reactiveops/ci-images/v11-alpine/Dockerfile
Added image to fix image pull issue mentioned in [CASMPET-6911](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6911)
- Were the …
=> Added alpine image to fix issue with cray-vpa

.github/workflows/docker.io.victoriametrics.operator.v0.46.4.yaml, .github/workflows/docker.io.victoriametrics.vmagent.v1.102.1.yaml, .github/workflows/docker.io.victoriametrics.vminsert.v1.102.1-cluster.yaml, .github/workflows/docker.io.victoriametrics.vmselect.v1.102.1-cluster.yaml, .github/workflows/docker.io.victoriametrics.vmstorage.v1.102.1-cluster.yaml, docker.io/victoriametrics/operator/v0.46.4/Dockerfile, docker.io/victoriametrics/vmagent/v1.102.1/Dockerfile, docker.io/victoriametrics/vminsert/v1.102.1-cluster/Dockerfile, docker.io/victoriametrics/vmselect/v1.102.1-cluster/Dockerfile, docker.io/victoriametrics/vmstorage/v1.102.1-cluster/Dockerfile
Push all the images to the Arti and update image in values.yaml for Victoria metrics
[
* Merge with/before/after `<insert PR URL here>`](https://jira-pro.it.hpe.com:8443/browse/CASMMON-459)
Mug
=> CASMMON-458 Upgrade victoria metrics images to the Arti and update image in values.yaml for Victoria metrics

.github/workflows/ghcr.io.banzaicloud.vault-operator.1.19.0.yaml, ghcr.io/banzaicloud/vault-operator/1.19.0/Dockerfile
Add image for vault-operator v1.19.0 to upgrade cray-vault-operator for CSM 1.7.
* Part of [CASM-5241](https://jira-pro.it.hpe.com:8443/browse/CASM-5241)
To test this, I first put something into vault in a test location, then upgraded vault-operator and ensured I was still able to access the data.
Putting in data:
```
/ # export VAULT_ADDR=http://127.0.0.1:8200
/ # vault secrets enable -version=2 kv
/ # vault kv put kv/testdata key1="value1" key2="value2"
== Secret Path ==
kv/data/testdata
======= Metadata =======
Key                Value
---                -----
created_time       2025-01-22T23:16:07.08820513Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1
/ # vault kv get kv/testdata
== Secret Path ==
kv/data/testdata …
```
=> CASM-5241: Add image for vault operator v1.19.0

.github/workflows/quay.io.arkmq-org.activemq-artemis-broker-init.2.0.0.yaml, .github/workflows/quay.io.arkmq-org.activemq-artemis-broker-kubernetes.2.0.0.yaml, .github/workflows/quay.io.arkmq-org.activemq-artemis-operator.2.0.0.yaml, quay.io/arkmq-org/activemq-artemis-broker-init/2.0.0/Dockerfile, quay.io/arkmq-org/activemq-artemis-broker-kubernetes/2.0.0/Dockerfile, quay.io/arkmq-org/activemq-artemis-operator/2.0.0/Dockerfile
The ActiveMQ Artemis project is in active development and is currently at v2.39.0 we are using version 2.34.0 which was release over a year ago. Security scan of the v2.34.0 version of the broker lists 7 critical security issues. We want to move to a newer version that has fewer vulnerabilities. Also would like to pick up bug fixes.  Artemis 2.39.0 was released 1-29-2025 and that is the reason for the second PR.   I will close the first one for the 2.38.0 version.
The newer broker and kubernetes operator images are backward compatible with the DVS MQTT client …
=> USS-3144: Add Artemis 2.39.0 and operator docker images

.github/workflows/docker.io.kuskoman.logstash-exporter.v1.9.0.yaml, docker.io/kuskoman/logstash-exporter/v1.9.0/Dockerfile
- Related to https://jira-pro.it.hpe.com:8443/browse/CASMMON-485
=> CASMMON-485 upgrade logstash-exporter docker image to 1.9.0

.github/workflows/docker.io.bitnami.kube-state-metrics.2.15.0.yaml, docker.io/bitnami/kube-state-metrics/2.15.0/Dockerfile
Generate image with latest `kube-state-metrics` version (2.15.0) available in bitnami. This image will be used in `cray-sysmgmt-health` chart, if testing goes well.
* Future work required by [CASMPET-6561](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6561)
On `molly` running k8s 1.32, successfully installed helm chart using `kube-state-metrics` 2.15.0.
```
ncn-m001:~/studenym/cray-sysmgmt-health # helm upgrade -n sysmgmt-health cray-sysmgmt-health .
Release "cray-sysmgmt-health" has been upgraded. Happy Helming!
NAME: cray-sysmgmt-health
LAST DEPLOYED: Thu Mar 20 18:50:24 2025
NAMESPACE: sysmgmt-health
STATUS: deployed
REVISION: 4
ncn-m001:~/studenym/cray-sysmgmt-health # …
```
=> CASMPET-6561: Generate latest kube-state-metrics image

.github/workflows/docker.io.grok-exporter.grok-exporter.v1.0.0.RC5.yaml, docker.io/grok-exporter/grok-exporter/v1.0.0.RC5/Dockerfile
create grok exporter docker image cray-sysmgmt-health
* Related to https://jira-pro.it.hpe.com:8443/browse/CASMMON-511
* wasp
=> CASMMON-511 create grok exporter docker image cray-sysmgmt-health

.github/workflows/quay.io.metallb.controller.v0.14.9.yaml, .github/workflows/quay.io.metallb.speaker.v0.14.9.yaml, quay.io/metallb/controller/v0.14.9/Dockerfile, quay.io/metallb/speaker/v0.14.9/Dockerfile
Add metallb v0.14.9 speaker and controller images for CSM 1.7.
* Related to [CASMPET-7388](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7388)
* Chart PR: https://github.com/Cray-HPE/cray-metallb/pull/14)
Old image:
Test service:
```
apiVersion: v1
kind: Service
metadata:
name: test-service
namespace: default
spec:
selector:
app: test-app
ports:
- protocol: TCP
port: 80
targetPort: 80
type: LoadBalancer
```
Correctly assigned IP:
```
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
test-service   LoadBalancer   10.22.112.80   10.103.5.67   80:31610/TCP   10m
```
Truncated logs from controller showing IP allocation:
```
...
{"caller":"level.go:63","event":"ipAllocated","ip":"10.92.100.83","level":"info","msg":"IP address assigned by …
```
=> CASMPET-7388: Add metallb v0.14.9 speaker and controller images

.github/workflows/registry.k8s.io.pause.3.9.yaml, registry.k8s.io/pause/3.9/Dockerfile
=> CASMPET-7532: Add pause 3.9

.github/workflows/quay.io.cilium.hubble-ui-backend.v0.13.2.yaml, .github/workflows/quay.io.cilium.hubble-ui.v0.13.2.yaml, quay.io/cilium/hubble-ui-backend/v0.13.2/Dockerfile, quay.io/cilium/hubble-ui/v0.13.2/Dockerfile
Import version v0.13.2 of quay.io/cilium/hubble-ui and quay.io/cilium/hubble-ui-backend to fix CVEs
* Resolves [CASMNET-2343](https://jira-pro.it.hpe.com:8443/browse/CASMNET-2343)
=> CASMNET-2343 - Fix CVEs in hubble-ui

.github/workflows/quay.io.arkmq-org.activemq-artemis-broker-init.2.0.6.yaml, .github/workflows/quay.io.arkmq-org.activemq-artemis-broker-kubernetes.2.0.6.yaml, .github/workflows/quay.io.arkmq-org.activemq-artemis-operator.2.0.6.yaml, quay.io/arkmq-org/activemq-artemis-broker-init/2.0.6/Dockerfile, quay.io/arkmq-org/activemq-artemis-broker-kubernetes/2.0.6/Dockerfile, quay.io/arkmq-org/activemq-artemis-operator/2.0.6/Dockerfile
Adding the container images that utilize Artemis MQTT broker 2.42.0 which contains a critical fix for CAST-38825.  The broker can experience thread starvation if a large number of connection/disconnections occur to the broker. The Artemis 2.42.0 broker contains this critical bug fix that resolves the issue https://issues.apache.org/jira/browse/ARTEMIS-5499
These container images will also be used in the USS-1.5.0 release and add to any patch release of USS-1.4.0.
This is a backwards compatible bugfix
* Resolves [USS-6927](https://jira-pro.it.hpe.com:8443/browse/USS-6927)
* Change will also be needed in `hpc-dvs-broker` and `hpc-shasta-os-uss-product-stream` repos
* Future work …
=> USS-5867: Add Artemis 2.42.0 container images
